const fs = require("fs");
const path = require("path");
const zlib = require("zlib");

const BRAND_NAME = "C.M.K Gatsibo";
const LOGO_PATH = path.resolve(__dirname, "../../assets/logo.png");

const formatDateTime = (value = new Date()) => {
    const date = new Date(value);
    return {
        date: date.toISOString().split("T")[0],
        time: date.toISOString().split("T")[1].slice(0, 8)
    };
};

const escapePdf = (value) => String(value ?? "")
    .replace(/\\/g, "\\\\")
    .replace(/\(/g, "\\(")
    .replace(/\)/g, "\\)");

const fit = (value, length) => {
    const text = String(value ?? "-");
    return text.length > length ? `${text.slice(0, Math.max(0, length - 3))}...` : text;
};

const buildTextLines = ({ title, reportNumber, company, generatedBy, preparedBy, reviewedBy, approvedBy, summary = [], insights = [], columns = [], rows = [] }) => {
    const generated = formatDateTime();
    const companyName = company?.company_name || "Mining Company";
    const companyInfo = [
        company?.address,
        company?.phone,
        company?.email
    ].filter(Boolean).join(" | ");
    const lines = [
        companyName,
        companyInfo || "Company information",
        "",
        "REPORT DETAILS",
        `Report Number: ${reportNumber}`,
        `Generated Date: ${generated.date}`,
        `Generated Time: ${generated.time}`,
        `Generated By: ${generatedBy || "-"}`,
        `Prepared By: ${preparedBy || generatedBy || "-"}`,
        reviewedBy ? `Reviewed By: ${reviewedBy}` : null,
        approvedBy ? `Approved By: ${approvedBy}` : null,
        "",
        "Summary"
    ].filter((line) => line !== null);

    summary.forEach((item) => lines.push(`${item.label}: ${item.value}`));
    if (insights.length) {
        lines.push("", "MANAGEMENT INSIGHTS");
        insights.forEach((item) => lines.push(`- ${item}`));
    }
    lines.push("");

    if (columns.length) {
        lines.push(columns.map((column) => fit(column.label, column.width || 16).padEnd(column.width || 16)).join(" "));
        lines.push(columns.map((column) => "-".repeat(column.width || 16)).join(" "));
        rows.forEach((row) => {
            lines.push(columns.map((column) => fit(row[column.key], column.width || 16).padEnd(column.width || 16)).join(" "));
        });
    } else {
        lines.push("No rows available for the selected filters.");
    }

    lines.push("");
    lines.push(`End of report | ${BRAND_NAME} | Data generated from live system records`);
    return lines;
};

// Converts the supplied non-interlaced 8-bit PNG logo into PDF image streams.
// Keeping this local avoids adding a heavyweight PDF dependency to the backend.
const readLogo = () => {
    try {
        const file = fs.readFileSync(LOGO_PATH);
        if (file.toString("ascii", 1, 4) !== "PNG") return null;

        let offset = 8;
        let width;
        let height;
        let bitDepth;
        let colorType;
        const dataChunks = [];
        while (offset + 12 <= file.length) {
            const length = file.readUInt32BE(offset);
            const type = file.toString("ascii", offset + 4, offset + 8);
            const start = offset + 8;
            const end = start + length;
            if (end + 4 > file.length) return null;
            if (type === "IHDR") {
                width = file.readUInt32BE(start);
                height = file.readUInt32BE(start + 4);
                bitDepth = file[start + 8];
                colorType = file[start + 9];
            } else if (type === "IDAT") dataChunks.push(file.subarray(start, end));
            else if (type === "IEND") break;
            offset = end + 4;
        }
        if (!width || !height || bitDepth !== 8 || ![2, 6].includes(colorType)) return null;

        const channels = colorType === 6 ? 4 : 3;
        const rowLength = width * channels;
        const packed = zlib.inflateSync(Buffer.concat(dataChunks));
        const decoded = Buffer.alloc(rowLength * height);
        let source = 0;
        let previous = Buffer.alloc(rowLength);
        for (let row = 0; row < height; row += 1) {
            const filter = packed[source++];
            const current = Buffer.alloc(rowLength);
            for (let x = 0; x < rowLength; x += 1) {
                const raw = packed[source++];
                const left = x >= channels ? current[x - channels] : 0;
                const up = previous[x];
                const upLeft = x >= channels ? previous[x - channels] : 0;
                if (filter === 0) current[x] = raw;
                else if (filter === 1) current[x] = (raw + left) & 255;
                else if (filter === 2) current[x] = (raw + up) & 255;
                else if (filter === 3) current[x] = (raw + Math.floor((left + up) / 2)) & 255;
                else if (filter === 4) {
                    const p = left + up - upLeft;
                    const pa = Math.abs(p - left), pb = Math.abs(p - up), pc = Math.abs(p - upLeft);
                    current[x] = (raw + (pa <= pb && pa <= pc ? left : pb <= pc ? up : upLeft)) & 255;
                } else return null;
            }
            current.copy(decoded, row * rowLength);
            previous = current;
        }

        const rgb = Buffer.alloc(width * height * 3);
        const alpha = colorType === 6 ? Buffer.alloc(width * height) : null;
        for (let pixel = 0; pixel < width * height; pixel += 1) {
            decoded.copy(rgb, pixel * 3, pixel * channels, pixel * channels + 3);
            if (alpha) alpha[pixel] = decoded[pixel * channels + 3];
        }
        return { width, height, rgb: zlib.deflateSync(rgb), alpha: alpha && zlib.deflateSync(alpha) };
    } catch (_) {
        return null;
    }
};

const pdfText = (value) => escapePdf(String(value ?? "-").replace(/[\u2013\u2014]/g, "-").replace(/[^\x20-\x7E]/g, ""));
const wrapCell = (value, width, fontSize) => {
    const text = String(value ?? "-").replace(/\s+/g, " ").trim() || "-";
    const maxChars = Math.max(4, Math.floor(width / (fontSize * 0.53)));
    const words = text.split(" "); const lines = []; let line = "";
    words.forEach((word) => {
        if (!line) line = word;
        else if (`${line} ${word}`.length <= maxChars) line += ` ${word}`;
        else { lines.push(line); line = word; }
    });
    if (line) lines.push(line);
    return lines.flatMap((line) => line.length <= maxChars ? [line] : Array.from({ length: Math.ceil(line.length / maxChars) }, (_, i) => line.slice(i * maxChars, (i + 1) * maxChars)));
};

const createPdfBuffer = (options) => {
    const columns = options.columns || [];
    const rows = options.rows || [];
    const landscape = columns.length > 7;
    const pageWidth = landscape ? 792 : 612;
    const pageHeight = landscape ? 612 : 792;
    const marginX = 30;
    const usableWidth = pageWidth - (marginX * 2);
    const pageBottom = 42;
    const headerHeight = 82;
    const fontSize = columns.length > 9 ? 5.6 : columns.length > 7 ? 6.3 : 7.2;
    const headerFontSize = Math.max(fontSize, 6.5);
    const weightTotal = columns.reduce((sum, column) => sum + Number(column.width || 12), 0) || 1;
    const widths = columns.map((column) => usableWidth * (Number(column.width || 12) / weightTotal));
    const generated = formatDateTime();
    const companyName = options.company?.company_name || "Mining Company";
    const companyInfo = [options.company?.address, options.company?.phone, options.company?.email].filter(Boolean).join(" | ");
    const pages = [];
    let rowIndex = 0;
    let firstPage = true;
    while (firstPage || rowIndex < rows.length) {
        const tableTop = firstPage ? pageHeight - 222 : pageHeight - 116;
        const tableHeaderHeight = 22;
        let cursorY = tableTop - tableHeaderHeight;
        const pageRows = [];
        while (rowIndex < rows.length) {
            const cellLines = columns.map((column, columnIndex) => wrapCell(rows[rowIndex][column.key], widths[columnIndex] - 8, fontSize));
            const rowHeight = Math.max(19, Math.min(54, Math.max(...cellLines.map((lines) => lines.length)) * (fontSize + 2) + 8));
            if (cursorY - rowHeight < pageBottom && pageRows.length) break;
            if (cursorY - rowHeight < pageBottom && !pageRows.length) { pageRows.push({ row: rows[rowIndex], cellLines, rowHeight: Math.max(19, pageBottom - 4) }); rowIndex += 1; break; }
            pageRows.push({ row: rows[rowIndex], cellLines, rowHeight }); cursorY -= rowHeight; rowIndex += 1;
        }
        pages.push({ firstPage, tableTop, pageRows });
        firstPage = false;
        if (!rows.length) break;
    }

    const objects = [];
    const addObject = (body) => {
        objects.push(Buffer.isBuffer(body) ? body : Buffer.from(body, "binary"));
        return objects.length;
    };

    const logo = readLogo();
    let logoId = null;
    let alphaId = null;
    if (logo?.alpha) {
        alphaId = addObject(Buffer.concat([
            Buffer.from(`<< /Type /XObject /Subtype /Image /Width ${logo.width} /Height ${logo.height} /ColorSpace /DeviceGray /BitsPerComponent 8 /Filter /FlateDecode /Length ${logo.alpha.length} >>\nstream\n`, "binary"),
            logo.alpha,
            Buffer.from("\nendstream", "binary")
        ]));
    }
    if (logo) {
        logoId = addObject(Buffer.concat([
            Buffer.from(`<< /Type /XObject /Subtype /Image /Width ${logo.width} /Height ${logo.height} /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /FlateDecode /Length ${logo.rgb.length}${alphaId ? ` /SMask ${alphaId} 0 R` : ""} >>\nstream\n`, "binary"),
            logo.rgb,
            Buffer.from("\nendstream", "binary")
        ]));
    }
    const fontId = addObject("<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>");
    const pageIds = [];

    pages.forEach((page, pageIndex) => {
        const textCommands = [
            `q 0.96 0.98 0.98 rg 0 0 ${pageWidth} ${pageHeight - headerHeight} re f Q`,
            `q 0.10 0.24 0.20 rg 0 ${pageHeight - headerHeight} ${pageWidth} ${headerHeight} re f Q`,
            ...(logoId ? ["q", `85 0 0 25 ${marginX} ${pageHeight - 55} cm`, "/Logo Do", "Q"] : []),
            `BT /F1 20 Tf 1 1 1 rg ${logoId ? 132 : marginX} ${pageHeight - 35} Td (${pdfText(options.title || "Operations Report")}) Tj ET`,
            `BT /F1 9 Tf 0.86 0.94 0.90 rg ${logoId ? 132 : marginX} ${pageHeight - 54} Td (${pdfText(BRAND_NAME + " | Printable operational report")}) Tj ET`
        ];
        const drawText = (text, x, y, size = fontSize, colour = "0.10 0.16 0.19") => textCommands.push(`BT /F1 ${size} Tf ${colour} rg ${x.toFixed(2)} ${y.toFixed(2)} Td (${pdfText(text)}) Tj ET`);
        const drawBox = (x, y, w, h, fill, stroke = "0.72 0.77 0.76") => {
            if (fill) textCommands.push(`q ${fill} rg ${x.toFixed(2)} ${y.toFixed(2)} ${w.toFixed(2)} ${h.toFixed(2)} re f Q`);
            textCommands.push(`q ${stroke} RG 0.45 w ${x.toFixed(2)} ${y.toFixed(2)} ${w.toFixed(2)} ${h.toFixed(2)} re S Q`);
        };

        if (page.firstPage) {
            drawText(companyName, marginX, pageHeight - 102, 11, "0.10 0.16 0.19");
            drawText(companyInfo || "Company information", marginX, pageHeight - 116, 7);
            drawText(`Report No: ${options.reportNumber || "-"}`, marginX, pageHeight - 136, 7);
            drawText(`Generated: ${generated.date} ${generated.time}`, marginX, pageHeight - 148, 7);
            drawText(`Generated by: ${options.generatedBy || "-"}`, marginX, pageHeight - 160, 7);
            const summaries = options.summary || [];
            summaries.slice(0, 6).forEach((item, index) => {
                const col = index % 3; const row = Math.floor(index / 3);
                const x = marginX + col * (usableWidth / 3); const y = pageHeight - 188 - row * 18;
                drawBox(x, y, usableWidth / 3 - 7, 15, "0.88 0.94 0.91");
                drawText(`${item.label}: ${item.value}`, x + 4, y + 5, 6.5, "0.10 0.25 0.20");
            });
        } else drawText(`Continued: ${options.title || "Operations Report"}`, marginX, pageHeight - 101, 8, "0.10 0.25 0.20");

        // Real table: cells are drawn independently, so data remains aligned
        // regardless of name length, currency value, or a wrapped remark.
        let x = marginX;
        columns.forEach((column, index) => { drawBox(x, page.tableTop - 22, widths[index], 22, "0.10 0.24 0.20", "0.10 0.24 0.20"); wrapCell(column.label, widths[index] - 7, headerFontSize).slice(0, 2).forEach((line, lineIndex) => drawText(line, x + 4, page.tableTop - 10 - lineIndex * (headerFontSize + 1), headerFontSize, "1 1 1")); x += widths[index]; });
        let y = page.tableTop - 22;
        page.pageRows.forEach(({ cellLines, rowHeight }, rowIndex) => {
            y -= rowHeight; x = marginX;
            columns.forEach((column, columnIndex) => { drawBox(x, y, widths[columnIndex], rowHeight, rowIndex % 2 ? "0.97 0.99 0.98" : "1 1 1"); cellLines[columnIndex].slice(0, 5).forEach((line, lineIndex) => drawText(line, x + 4, y + rowHeight - 10 - lineIndex * (fontSize + 2), fontSize)); x += widths[columnIndex]; });
        });
        if (!page.pageRows.length) { drawBox(marginX, page.tableTop - 48, usableWidth, 26, "1 1 1"); drawText("No records available for the selected filters.", marginX + 6, page.tableTop - 38, 8); }
        drawText(`Page ${pageIndex + 1} of ${pages.length} | ${BRAND_NAME} | Live system data`, pageWidth / 2 - 110, 22, 7, "0.30 0.37 0.35");

        const stream = textCommands.join("\n");
        const contentId = addObject(`<< /Length ${Buffer.byteLength(stream)} >>\nstream\n${stream}\nendstream`);
        const resources = `/Font << /F1 ${fontId} 0 R >>${logoId ? ` /XObject << /Logo ${logoId} 0 R >>` : ""}`;
        const pageId = addObject(`<< /Type /Page /Parent 0 0 R /MediaBox [0 0 ${pageWidth} ${pageHeight}] /Resources << ${resources} >> /Contents ${contentId} 0 R >>`);
        pageIds.push(pageId);
    });

    const pagesId = addObject(`<< /Type /Pages /Kids [${pageIds.map((id) => `${id} 0 R`).join(" ")}] /Count ${pageIds.length} >>`);
    pageIds.forEach((pageId) => {
        objects[pageId - 1] = Buffer.from(objects[pageId - 1].toString("binary").replace("/Parent 0 0 R", `/Parent ${pagesId} 0 R`), "binary");
    });
    const catalogId = addObject(`<< /Type /Catalog /Pages ${pagesId} 0 R >>`);

    let pdf = Buffer.from("%PDF-1.4\n", "binary");
    const offsets = [0];
    objects.forEach((body, index) => {
        offsets.push(pdf.length);
        pdf = Buffer.concat([pdf, Buffer.from(`${index + 1} 0 obj\n`, "binary"), body, Buffer.from("\nendobj\n", "binary")]);
    });

    const xrefOffset = pdf.length;
    let trailer = `xref\n0 ${objects.length + 1}\n`;
    trailer += "0000000000 65535 f \n";
    offsets.slice(1).forEach((offset) => {
        trailer += `${String(offset).padStart(10, "0")} 00000 n \n`;
    });
    trailer += `trailer\n<< /Size ${objects.length + 1} /Root ${catalogId} 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`;

    return Buffer.concat([pdf, Buffer.from(trailer, "binary")]);
};

module.exports = {
    createPdfBuffer,
    formatDateTime
};
