const formatDateTime = (value = new Date()) => {
    const date = new Date(value);
    return {
        date: date.toISOString().split("T")[0],
        time: date.toISOString().split("T")[1].slice(0, 8)
    };
};

const escapePdf = (value) => String(value ?? "")
    .replace(/\\/g, "\\\\")
    .replace(/\(/g, "\\(")
    .replace(/\)/g, "\\)");

const fit = (value, length) => {
    const text = String(value ?? "-");
    return text.length > length ? `${text.slice(0, Math.max(0, length - 3))}...` : text;
};

const buildTextLines = ({ title, reportNumber, company, generatedBy, preparedBy, reviewedBy, approvedBy, summary = [], columns = [], rows = [] }) => {
    const generated = formatDateTime();
    const companyName = company?.company_name || "Mining Company";
    const companyInfo = [
        company?.address,
        company?.phone,
        company?.email
    ].filter(Boolean).join(" | ");
    const lines = [
        "MineWise Operations Suite",
        companyName,
        companyInfo || "Company information",
        "",
        title,
        `Report Number: ${reportNumber}`,
        `Generated Date: ${generated.date}`,
        `Generated Time: ${generated.time}`,
        `Generated By: ${generatedBy || "-"}`,
        `Prepared By: ${preparedBy || generatedBy || "-"}`,
        reviewedBy ? `Reviewed By: ${reviewedBy}` : null,
        approvedBy ? `Approved By: ${approvedBy}` : null,
        "",
        "Summary"
    ].filter((line) => line !== null);

    summary.forEach((item) => lines.push(`${item.label}: ${item.value}`));
    lines.push("");

    if (columns.length) {
        lines.push(columns.map((column) => fit(column.label, column.width || 16).padEnd(column.width || 16)).join(" "));
        lines.push(columns.map((column) => "-".repeat(column.width || 16)).join(" "));
        rows.forEach((row) => {
            lines.push(columns.map((column) => fit(row[column.key], column.width || 16).padEnd(column.width || 16)).join(" "));
        });
    } else {
        lines.push("No rows available for the selected filters.");
    }

    lines.push("");
    lines.push("Footer: MineWise Operations Suite - Confidential company report");
    return lines;
};

const createPdfBuffer = (options) => {
    const lines = buildTextLines(options);
    const pageWidth = 612;
    const pageHeight = 792;
    const marginX = 42;
    const startY = 744;
    const lineHeight = 13;
    const maxLinesPerPage = 50;
    const pages = [];

    for (let index = 0; index < lines.length; index += maxLinesPerPage) {
        pages.push(lines.slice(index, index + maxLinesPerPage));
    }

    const objects = [];
    const addObject = (body) => {
        objects.push(body);
        return objects.length;
    };

    const fontId = addObject("<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>");
    const pageIds = [];

    pages.forEach((pageLines, pageIndex) => {
        const textCommands = [
            "BT",
            "/F1 9 Tf",
            `${marginX} ${startY} Td`
        ];

        pageLines.forEach((line, lineIndex) => {
            if (lineIndex > 0) textCommands.push(`0 -${lineHeight} Td`);
            textCommands.push(`(${escapePdf(line)}) Tj`);
        });

        textCommands.push("ET");
        textCommands.push("BT /F1 8 Tf 270 24 Td");
        textCommands.push(`(Page ${pageIndex + 1} of ${pages.length}) Tj`);
        textCommands.push("ET");

        const stream = textCommands.join("\n");
        const contentId = addObject(`<< /Length ${Buffer.byteLength(stream)} >>\nstream\n${stream}\nendstream`);
        const pageId = addObject(`<< /Type /Page /Parent 0 0 R /MediaBox [0 0 ${pageWidth} ${pageHeight}] /Resources << /Font << /F1 ${fontId} 0 R >> >> /Contents ${contentId} 0 R >>`);
        pageIds.push(pageId);
    });

    const pagesId = addObject(`<< /Type /Pages /Kids [${pageIds.map((id) => `${id} 0 R`).join(" ")}] /Count ${pageIds.length} >>`);
    pageIds.forEach((pageId) => {
        objects[pageId - 1] = objects[pageId - 1].replace("/Parent 0 0 R", `/Parent ${pagesId} 0 R`);
    });
    const catalogId = addObject(`<< /Type /Catalog /Pages ${pagesId} 0 R >>`);

    let pdf = "%PDF-1.4\n";
    const offsets = [0];
    objects.forEach((body, index) => {
        offsets.push(Buffer.byteLength(pdf));
        pdf += `${index + 1} 0 obj\n${body}\nendobj\n`;
    });

    const xrefOffset = Buffer.byteLength(pdf);
    pdf += `xref\n0 ${objects.length + 1}\n`;
    pdf += "0000000000 65535 f \n";
    offsets.slice(1).forEach((offset) => {
        pdf += `${String(offset).padStart(10, "0")} 00000 n \n`;
    });
    pdf += `trailer\n<< /Size ${objects.length + 1} /Root ${catalogId} 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`;

    return Buffer.from(pdf, "binary");
};

module.exports = {
    createPdfBuffer,
    formatDateTime
};
