-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.admins (
  admin_id uuid NOT NULL DEFAULT gen_random_uuid(),
  username text NOT NULL UNIQUE,
  password text NOT NULL,
  full_name text NOT NULL,
  phone text UNIQUE,
  email text UNIQUE,
  status USER-DEFINED DEFAULT 'ACTIVE'::account_status,
  last_login timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT admins_pkey PRIMARY KEY (admin_id)
);
CREATE TABLE public.companies (
  company_id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_name text NOT NULL,
  mining_license_number text UNIQUE,
  tin_number text UNIQUE,
  phone text,
  email text,
  province text,
  district text,
  sector text,
  village text,
  address text,
  registration_date date,
  status USER-DEFINED DEFAULT 'ACTIVE'::account_status,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT companies_pkey PRIMARY KEY (company_id)
);
CREATE TABLE public.roles (
  role_id uuid NOT NULL DEFAULT gen_random_uuid(),
  role_name text NOT NULL UNIQUE,
  description text,
  CONSTRAINT roles_pkey PRIMARY KEY (role_id)
);
CREATE TABLE public.departments (
  department_id uuid NOT NULL DEFAULT gen_random_uuid(),
  department_name text NOT NULL UNIQUE,
  description text,
  created_at timestamp with time zone DEFAULT now(),
  company_id uuid,
  CONSTRAINT departments_pkey PRIMARY KEY (department_id),
  CONSTRAINT departments_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(company_id)
);
CREATE TABLE public.positions (
  position_id uuid NOT NULL DEFAULT gen_random_uuid(),
  position_name text NOT NULL,
  description text,
  created_at timestamp with time zone DEFAULT now(),
  daily_salary numeric,
  company_id uuid,
  CONSTRAINT positions_pkey PRIMARY KEY (position_id),
  CONSTRAINT fk_positions_company FOREIGN KEY (company_id) REFERENCES public.companies(company_id)
);
CREATE TABLE public.employees (
  employee_id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL,
  position_id uuid,
  employee_code text NOT NULL UNIQUE,
  first_name text NOT NULL,
  last_name text NOT NULL,
  gender USER-DEFINED NOT NULL,
  date_of_birth date NOT NULL,
  national_id character varying NOT NULL UNIQUE,
  phone text NOT NULL,
  email text,
  address text NOT NULL,
  hire_date date NOT NULL,
  monthly_salary numeric DEFAULT 0,
  daily_rate numeric DEFAULT 0,
  profile_photo text,
  status USER-DEFINED DEFAULT 'ACTIVE'::employee_status,
  created_at timestamp with time zone DEFAULT now(),
  manager_user_id uuid,
  CONSTRAINT employees_pkey PRIMARY KEY (employee_id),
  CONSTRAINT fk_employee_position FOREIGN KEY (position_id) REFERENCES public.positions(position_id),
  CONSTRAINT fk_employee_company FOREIGN KEY (company_id) REFERENCES public.companies(company_id),
  CONSTRAINT employees_manager_user_id_fkey FOREIGN KEY (manager_user_id) REFERENCES public.users(user_id)
);
CREATE TABLE public.users (
  user_id uuid NOT NULL DEFAULT gen_random_uuid(),
  employee_id uuid UNIQUE,
  role_id uuid NOT NULL,
  username text NOT NULL UNIQUE,
  password text NOT NULL,
  is_active boolean DEFAULT true,
  last_login timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT users_pkey PRIMARY KEY (user_id),
  CONSTRAINT fk_user_employee FOREIGN KEY (employee_id) REFERENCES public.employees(employee_id),
  CONSTRAINT fk_user_role FOREIGN KEY (role_id) REFERENCES public.roles(role_id)
);
CREATE TABLE public.attendance (
  attendance_id uuid NOT NULL DEFAULT gen_random_uuid(),
  employee_id uuid NOT NULL,
  attendance_date date NOT NULL,
  check_in time without time zone,
  check_out time without time zone,
  hours_worked numeric DEFAULT 0,
  overtime_hours numeric DEFAULT 0,
  attendance_status USER-DEFINED DEFAULT 'PRESENT'::attendance_status,
  remarks text,
  created_at timestamp with time zone DEFAULT now(),
  company_id uuid,
  recorded_by uuid,
  manager_user_id uuid,
  CONSTRAINT attendance_pkey PRIMARY KEY (attendance_id),
  CONSTRAINT fk_attendance_employee FOREIGN KEY (employee_id) REFERENCES public.employees(employee_id),
  CONSTRAINT attendance_recorded_by_fkey FOREIGN KEY (recorded_by) REFERENCES public.users(user_id),
  CONSTRAINT attendance_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(company_id),
  CONSTRAINT attendance_manager_user_id_fkey FOREIGN KEY (manager_user_id) REFERENCES public.users(user_id)
);
CREATE TABLE public.production_records (
  production_id uuid NOT NULL DEFAULT gen_random_uuid(),
  employee_id uuid NOT NULL,
  production_date date NOT NULL,
  mineral_type text NOT NULL,
  quantity numeric NOT NULL,
  unit text DEFAULT 'KG'::text,
  remarks text,
  created_at timestamp with time zone DEFAULT now(),
  unit_price numeric CHECK (unit_price IS NULL OR unit_price >= 0::numeric),
  activity_details text,
  working_hours numeric CHECK (working_hours IS NULL OR working_hours >= 0::numeric),
  recorded_by uuid,
  manager_user_id uuid,
  CONSTRAINT production_records_pkey PRIMARY KEY (production_id),
  CONSTRAINT fk_production_employee FOREIGN KEY (employee_id) REFERENCES public.employees(employee_id),
  CONSTRAINT production_records_recorded_by_fkey FOREIGN KEY (recorded_by) REFERENCES public.users(user_id),
  CONSTRAINT production_records_manager_user_id_fkey FOREIGN KEY (manager_user_id) REFERENCES public.users(user_id)
);
CREATE TABLE public.expenses (
  expense_id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL,
  expense_category text NOT NULL,
  amount numeric NOT NULL,
  expense_date date NOT NULL,
  description text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT expenses_pkey PRIMARY KEY (expense_id),
  CONSTRAINT fk_expense_company FOREIGN KEY (company_id) REFERENCES public.companies(company_id)
);
CREATE TABLE public.salary_advances (
  advance_id uuid NOT NULL DEFAULT gen_random_uuid(),
  employee_id uuid NOT NULL,
  amount numeric NOT NULL,
  reason text,
  request_date date DEFAULT CURRENT_DATE,
  approval_date date,
  status USER-DEFINED DEFAULT 'PENDING'::advance_status,
  created_at timestamp with time zone DEFAULT now(),
  manager_reviewed_by uuid,
  manager_reviewed_at timestamp with time zone,
  manager_comments text,
  owner_reviewed_by uuid,
  owner_reviewed_at timestamp with time zone,
  owner_comments text,
  paid_by uuid,
  paid_at timestamp with time zone,
  payment_reference text,
  manager_approved_by uuid,
  manager_approved_at timestamp with time zone,
  manager_rejection_reason text,
  owner_approved_by uuid,
  owner_approved_at timestamp with time zone,
  owner_rejection_reason text,
  payment_status text NOT NULL DEFAULT 'UNPAID'::text,
  payment_date timestamp with time zone,
  amount_paid numeric NOT NULL DEFAULT 0 CHECK (amount_paid >= 0::numeric),
  amount_deducted numeric NOT NULL DEFAULT 0 CHECK (amount_deducted >= 0::numeric),
  remaining_balance numeric,
  deducted_by_payroll_id uuid,
  deduction_status text NOT NULL DEFAULT 'NOT_DEDUCTED'::text,
  payment_provider text,
  manager_user_id uuid,
  CONSTRAINT salary_advances_pkey PRIMARY KEY (advance_id),
  CONSTRAINT fk_advance_employee FOREIGN KEY (employee_id) REFERENCES public.employees(employee_id),
  CONSTRAINT salary_advances_manager_reviewed_by_fkey FOREIGN KEY (manager_reviewed_by) REFERENCES public.users(user_id),
  CONSTRAINT salary_advances_owner_reviewed_by_fkey FOREIGN KEY (owner_reviewed_by) REFERENCES public.users(user_id),
  CONSTRAINT salary_advances_paid_by_fkey FOREIGN KEY (paid_by) REFERENCES public.users(user_id),
  CONSTRAINT salary_advances_manager_approved_by_fkey FOREIGN KEY (manager_approved_by) REFERENCES public.users(user_id),
  CONSTRAINT salary_advances_owner_approved_by_fkey FOREIGN KEY (owner_approved_by) REFERENCES public.users(user_id),
  CONSTRAINT salary_advances_deducted_by_payroll_id_fkey FOREIGN KEY (deducted_by_payroll_id) REFERENCES public.payroll(payroll_id),
  CONSTRAINT salary_advances_manager_user_id_fkey FOREIGN KEY (manager_user_id) REFERENCES public.users(user_id)
);
CREATE TABLE public.payroll (
  payroll_id uuid NOT NULL DEFAULT gen_random_uuid(),
  employee_id uuid NOT NULL,
  payroll_month integer NOT NULL CHECK (payroll_month >= 1 AND payroll_month <= 12),
  payroll_year integer NOT NULL,
  days_worked numeric DEFAULT 0,
  overtime_hours numeric DEFAULT 0,
  basic_salary numeric DEFAULT 0,
  overtime_pay numeric DEFAULT 0,
  allowances numeric DEFAULT 0,
  deductions numeric DEFAULT 0,
  advance_deduction numeric DEFAULT 0,
  net_salary numeric DEFAULT 0,
  generated_at timestamp with time zone DEFAULT now(),
  payment_status text DEFAULT 'PENDING'::character varying CHECK (payment_status = ANY (ARRAY['PENDING'::text, 'GENERATED'::text, 'PENDING_MANAGER'::text, 'PENDING_OWNER'::text, 'APPROVED'::text, 'PAYMENT_PROCESSING'::text, 'PAID'::text, 'PARTIALLY_PAID'::text, 'FAILED'::text])),
  company_id uuid,
  approved_by uuid,
  approved_at timestamp with time zone,
  rejected_by uuid,
  rejected_at timestamp with time zone,
  rejection_reason text,
  manager_approved_by uuid,
  manager_approved_at timestamp with time zone,
  manager_rejected_by uuid,
  manager_rejected_at timestamp with time zone,
  manager_rejection_reason text,
  owner_approved_by uuid,
  owner_approved_at timestamp with time zone,
  owner_rejected_by uuid,
  owner_rejected_at timestamp with time zone,
  owner_rejection_reason text,
  approval_status text NOT NULL DEFAULT 'GENERATED'::text,
  locked_at timestamp with time zone,
  payroll_period_start date,
  payroll_period_end date,
  payroll_frequency text NOT NULL DEFAULT 'MONTHLY'::text CHECK (payroll_frequency = ANY (ARRAY['MONTHLY'::text, 'BIWEEKLY'::text])),
  consumption_deduction numeric NOT NULL DEFAULT 0 CHECK (consumption_deduction >= 0::numeric),
  manager_user_id uuid,
  CONSTRAINT payroll_pkey PRIMARY KEY (payroll_id),
  CONSTRAINT fk_payroll_employee FOREIGN KEY (employee_id) REFERENCES public.employees(employee_id),
  CONSTRAINT payroll_manager_rejected_by_fkey FOREIGN KEY (manager_rejected_by) REFERENCES public.users(user_id),
  CONSTRAINT payroll_owner_approved_by_fkey FOREIGN KEY (owner_approved_by) REFERENCES public.users(user_id),
  CONSTRAINT payroll_owner_rejected_by_fkey FOREIGN KEY (owner_rejected_by) REFERENCES public.users(user_id),
  CONSTRAINT payroll_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(company_id),
  CONSTRAINT payroll_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.users(user_id),
  CONSTRAINT payroll_rejected_by_fkey FOREIGN KEY (rejected_by) REFERENCES public.users(user_id),
  CONSTRAINT payroll_manager_approved_by_fkey FOREIGN KEY (manager_approved_by) REFERENCES public.users(user_id),
  CONSTRAINT payroll_manager_user_id_fkey FOREIGN KEY (manager_user_id) REFERENCES public.users(user_id)
);
CREATE TABLE public.salary_payments (
  payment_id uuid NOT NULL DEFAULT gen_random_uuid(),
  payroll_id uuid NOT NULL,
  payment_date date,
  payment_method text,
  transaction_reference text,
  amount numeric NOT NULL,
  payment_status USER-DEFINED DEFAULT 'PENDING'::payment_status,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT salary_payments_pkey PRIMARY KEY (payment_id),
  CONSTRAINT fk_payment_payroll FOREIGN KEY (payroll_id) REFERENCES public.payroll(payroll_id)
);
CREATE TABLE public.payments (
  payment_id uuid NOT NULL DEFAULT gen_random_uuid(),
  payroll_id uuid NOT NULL,
  employee_id uuid NOT NULL,
  phone character varying NOT NULL,
  beneficiary_name character varying NOT NULL,
  amount numeric NOT NULL CHECK (amount >= 0::numeric),
  payment_method character varying NOT NULL DEFAULT 'MOBILE_MONEY'::character varying,
  transaction_reference character varying,
  payment_status text NOT NULL DEFAULT 'PENDING'::character varying CHECK (payment_status = ANY (ARRAY['PENDING'::text, 'READY'::text, 'PROCESSING'::text, 'PAID'::text, 'FAILED'::text, 'SUCCESS'::text, 'FAILED_VALIDATION'::text, 'FAILED_NETWORK'::text, 'FAILED_INSUFFICIENT_BALANCE'::text, 'FAILED_UNKNOWN'::text])),
  failure_reason text,
  payment_date timestamp without time zone,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  company_id uuid,
  receiver_phone character varying,
  receiver_name character varying,
  transaction_id character varying,
  reference_id character varying,
  paid_at timestamp with time zone,
  created_by uuid,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  provider_name character varying,
  provider_response jsonb,
  manager_user_id uuid,
  CONSTRAINT payments_pkey PRIMARY KEY (payment_id),
  CONSTRAINT payments_payroll_id_fkey FOREIGN KEY (payroll_id) REFERENCES public.payroll(payroll_id),
  CONSTRAINT payments_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(employee_id),
  CONSTRAINT payments_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(company_id),
  CONSTRAINT payments_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(user_id),
  CONSTRAINT payments_manager_user_id_fkey FOREIGN KEY (manager_user_id) REFERENCES public.users(user_id)
);
CREATE TABLE public.reports (
  report_id uuid NOT NULL DEFAULT uuid_generate_v4(),
  company_id uuid,
  accountant_id uuid,
  report_date date NOT NULL,
  title text NOT NULL,
  report_content text NOT NULL,
  is_read boolean DEFAULT false,
  is_submitted boolean DEFAULT false,
  owner_edit_approved boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  status text NOT NULL DEFAULT 'DRAFT'::text CHECK (status = ANY (ARRAY['DRAFT'::text, 'PENDING_MANAGER'::text, 'PENDING_OWNER'::text, 'CHANGES_REQUESTED'::text, 'APPROVED'::text])),
  attendance_summary jsonb,
  production_summary jsonb,
  advances_summary jsonb,
  incidents text,
  daily_summary text,
  manager_reviewed_by uuid,
  manager_reviewed_at timestamp with time zone,
  manager_decision_reason text,
  owner_reviewed_by uuid,
  owner_reviewed_at timestamp with time zone,
  owner_decision_reason text,
  is_locked boolean NOT NULL DEFAULT false,
  pdf_file_name text,
  pdf_report_number text,
  pdf_generated_at timestamp with time zone,
  pdf_generated_by uuid,
  pdf_mime_type text,
  pdf_metadata jsonb,
  created_by uuid,
  locked_at timestamp with time zone,
  report_type text NOT NULL DEFAULT 'DAILY'::text CHECK (report_type = ANY (ARRAY['DAILY'::text, 'WEEKLY'::text, 'MONTHLY'::text, 'YEARLY'::text])),
  period_start date,
  period_end date,
  snapshot_generated_at timestamp with time zone,
  manager_user_id uuid,
  CONSTRAINT reports_pkey PRIMARY KEY (report_id),
  CONSTRAINT reports_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(company_id),
  CONSTRAINT reports_accountant_id_fkey FOREIGN KEY (accountant_id) REFERENCES public.employees(employee_id),
  CONSTRAINT reports_manager_reviewed_by_fkey FOREIGN KEY (manager_reviewed_by) REFERENCES public.users(user_id),
  CONSTRAINT reports_owner_reviewed_by_fkey FOREIGN KEY (owner_reviewed_by) REFERENCES public.users(user_id),
  CONSTRAINT reports_pdf_generated_by_fkey FOREIGN KEY (pdf_generated_by) REFERENCES public.users(user_id),
  CONSTRAINT reports_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(user_id),
  CONSTRAINT reports_manager_user_id_fkey FOREIGN KEY (manager_user_id) REFERENCES public.users(user_id)
);
CREATE TABLE public.company_owners (
  owner_id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL,
  first_name text NOT NULL,
  last_name text NOT NULL,
  phone text UNIQUE,
  email text UNIQUE,
  username text NOT NULL UNIQUE,
  password text NOT NULL,
  status USER-DEFINED DEFAULT 'ACTIVE'::account_status,
  last_login timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  owner_user_id uuid,
  CONSTRAINT company_owners_pkey PRIMARY KEY (owner_id),
  CONSTRAINT company_owners_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(company_id),
  CONSTRAINT company_owners_owner_user_id_fkey FOREIGN KEY (owner_user_id) REFERENCES public.users(user_id)
);
CREATE TABLE public.production_expenses (
  expense_id uuid NOT NULL DEFAULT gen_random_uuid(),
  production_id uuid NOT NULL,
  company_id uuid NOT NULL,
  expense_date date NOT NULL,
  description text NOT NULL,
  amount numeric NOT NULL CHECK (amount >= 0::numeric),
  recorded_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT production_expenses_pkey PRIMARY KEY (expense_id),
  CONSTRAINT production_expenses_production_id_fkey FOREIGN KEY (production_id) REFERENCES public.production_records(production_id),
  CONSTRAINT production_expenses_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(company_id),
  CONSTRAINT production_expenses_recorded_by_fkey FOREIGN KEY (recorded_by) REFERENCES public.users(user_id)
);
CREATE TABLE public.production_workers (
  production_worker_id uuid NOT NULL DEFAULT gen_random_uuid(),
  production_id uuid NOT NULL,
  employee_id uuid NOT NULL,
  working_hours numeric CHECK (working_hours IS NULL OR working_hours >= 0::numeric),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT production_workers_pkey PRIMARY KEY (production_worker_id),
  CONSTRAINT production_workers_production_id_fkey FOREIGN KEY (production_id) REFERENCES public.production_records(production_id),
  CONSTRAINT production_workers_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(employee_id)
);
CREATE TABLE public.salary_advance_deductions (
  deduction_id uuid NOT NULL DEFAULT gen_random_uuid(),
  advance_id uuid NOT NULL,
  payroll_id uuid NOT NULL,
  amount numeric NOT NULL CHECK (amount > 0::numeric),
  deducted_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  CONSTRAINT salary_advance_deductions_pkey PRIMARY KEY (deduction_id),
  CONSTRAINT salary_advance_deductions_advance_id_fkey FOREIGN KEY (advance_id) REFERENCES public.salary_advances(advance_id),
  CONSTRAINT salary_advance_deductions_payroll_id_fkey FOREIGN KEY (payroll_id) REFERENCES public.payroll(payroll_id),
  CONSTRAINT salary_advance_deductions_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(user_id)
);
CREATE TABLE public.food_suppliers (
  supplier_id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  company_id uuid NOT NULL,
  supplier_name text NOT NULL,
  phone character varying,
  email character varying,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  active boolean NOT NULL DEFAULT true,
  CONSTRAINT food_suppliers_pkey PRIMARY KEY (supplier_id),
  CONSTRAINT food_suppliers_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id),
  CONSTRAINT food_suppliers_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(company_id),
  CONSTRAINT food_suppliers_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(user_id)
);
CREATE TABLE public.food_supplies (
  food_supply_id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL,
  supplier_id uuid NOT NULL,
  supply_date date NOT NULL,
  notes text,
  status text NOT NULL DEFAULT 'PENDING_MANAGER'::text CHECK (status = ANY (ARRAY['DRAFT'::text, 'PENDING_MANAGER'::text, 'PENDING_OWNER'::text, 'CHANGES_REQUESTED'::text, 'OWNER_APPROVED'::text, 'PAID'::text])),
  manager_approved_by uuid,
  manager_approved_at timestamp with time zone,
  manager_comments text,
  owner_approved_by uuid,
  owner_approved_at timestamp with time zone,
  owner_comments text,
  payment_status text NOT NULL DEFAULT 'UNPAID'::text CHECK (payment_status = ANY (ARRAY['UNPAID'::text, 'PAID'::text, 'FAILED'::text])),
  payment_reference text,
  payment_provider text,
  paid_by uuid,
  paid_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  manager_user_id uuid,
  CONSTRAINT food_supplies_pkey PRIMARY KEY (food_supply_id),
  CONSTRAINT food_supplies_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(company_id),
  CONSTRAINT food_supplies_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.food_suppliers(supplier_id),
  CONSTRAINT food_supplies_manager_approved_by_fkey FOREIGN KEY (manager_approved_by) REFERENCES public.users(user_id),
  CONSTRAINT food_supplies_owner_approved_by_fkey FOREIGN KEY (owner_approved_by) REFERENCES public.users(user_id),
  CONSTRAINT food_supplies_paid_by_fkey FOREIGN KEY (paid_by) REFERENCES public.users(user_id),
  CONSTRAINT food_supplies_manager_user_id_fkey FOREIGN KEY (manager_user_id) REFERENCES public.users(user_id)
);
CREATE TABLE public.food_supply_items (
  food_supply_item_id uuid NOT NULL DEFAULT gen_random_uuid(),
  food_supply_id uuid NOT NULL,
  food_name text NOT NULL,
  quantity numeric NOT NULL CHECK (quantity > 0::numeric),
  unit text NOT NULL DEFAULT 'unit'::text,
  unit_price numeric NOT NULL CHECK (unit_price >= 0::numeric),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT food_supply_items_pkey PRIMARY KEY (food_supply_item_id),
  CONSTRAINT food_supply_items_food_supply_id_fkey FOREIGN KEY (food_supply_id) REFERENCES public.food_supplies(food_supply_id)
);
CREATE TABLE public.food_supply_payments (
  food_supply_payment_id uuid NOT NULL DEFAULT gen_random_uuid(),
  food_supply_id uuid NOT NULL UNIQUE,
  company_id uuid NOT NULL,
  supplier_id uuid NOT NULL,
  amount numeric NOT NULL CHECK (amount > 0::numeric),
  payment_status text NOT NULL CHECK (payment_status = ANY (ARRAY['PAID'::text, 'FAILED'::text])),
  provider_name text NOT NULL DEFAULT 'INTERNAL_TEST'::text,
  transaction_reference text,
  provider_response jsonb,
  failure_reason text,
  paid_by uuid,
  paid_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT food_supply_payments_pkey PRIMARY KEY (food_supply_payment_id),
  CONSTRAINT food_supply_payments_food_supply_id_fkey FOREIGN KEY (food_supply_id) REFERENCES public.food_supplies(food_supply_id),
  CONSTRAINT food_supply_payments_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(company_id),
  CONSTRAINT food_supply_payments_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.food_suppliers(supplier_id),
  CONSTRAINT food_supply_payments_paid_by_fkey FOREIGN KEY (paid_by) REFERENCES public.users(user_id)
);
CREATE TABLE public.worker_consumptions (
  consumption_id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL,
  employee_id uuid NOT NULL,
  consumption_date date NOT NULL,
  item_name text NOT NULL,
  quantity numeric NOT NULL DEFAULT 1 CHECK (quantity > 0::numeric),
  unit_price numeric NOT NULL CHECK (unit_price >= 0::numeric),
  total_amount numeric NOT NULL CHECK (total_amount >= 0::numeric),
  amount_deducted numeric NOT NULL DEFAULT 0 CHECK (amount_deducted >= 0::numeric),
  remaining_balance numeric NOT NULL CHECK (remaining_balance >= 0::numeric),
  recorded_by uuid,
  remarks text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  manager_user_id uuid,
  shopkeeper_id uuid,
  approval_status text NOT NULL DEFAULT 'PENDING_MANAGER'::text CHECK (approval_status = ANY (ARRAY['PENDING_MANAGER'::text, 'PENDING_OWNER'::text, 'CHANGES_REQUESTED'::text, 'OWNER_APPROVED'::text, 'PAID'::text])),
  manager_approved_by uuid,
  manager_approved_at timestamp with time zone,
  owner_approved_by uuid,
  owner_approved_at timestamp with time zone,
  approval_comments text,
  shopkeeper_payment_status text NOT NULL DEFAULT 'UNPAID'::text CHECK (shopkeeper_payment_status = ANY (ARRAY['UNPAID'::text, 'PAID'::text, 'FAILED'::text])),
  shopkeeper_payment_reference text,
  paid_at timestamp with time zone,
  CONSTRAINT worker_consumptions_pkey PRIMARY KEY (consumption_id),
  CONSTRAINT worker_consumptions_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(company_id),
  CONSTRAINT worker_consumptions_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(employee_id),
  CONSTRAINT worker_consumptions_recorded_by_fkey FOREIGN KEY (recorded_by) REFERENCES public.users(user_id),
  CONSTRAINT worker_consumptions_manager_user_id_fkey FOREIGN KEY (manager_user_id) REFERENCES public.users(user_id),
  CONSTRAINT worker_consumptions_shopkeeper_id_fkey FOREIGN KEY (shopkeeper_id) REFERENCES public.shopkeepers(shopkeeper_id),
  CONSTRAINT worker_consumptions_manager_approved_by_fkey FOREIGN KEY (manager_approved_by) REFERENCES public.users(user_id),
  CONSTRAINT worker_consumptions_owner_approved_by_fkey FOREIGN KEY (owner_approved_by) REFERENCES public.users(user_id)
);
CREATE TABLE public.worker_consumption_deductions (
  worker_consumption_deduction_id uuid NOT NULL DEFAULT gen_random_uuid(),
  consumption_id uuid NOT NULL,
  payroll_id uuid NOT NULL,
  amount numeric NOT NULL CHECK (amount > 0::numeric),
  deducted_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  CONSTRAINT worker_consumption_deductions_pkey PRIMARY KEY (worker_consumption_deduction_id),
  CONSTRAINT worker_consumption_deductions_consumption_id_fkey FOREIGN KEY (consumption_id) REFERENCES public.worker_consumptions(consumption_id),
  CONSTRAINT worker_consumption_deductions_payroll_id_fkey FOREIGN KEY (payroll_id) REFERENCES public.payroll(payroll_id),
  CONSTRAINT worker_consumption_deductions_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(user_id)
);
CREATE TABLE public.shopkeepers (
  shopkeeper_id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL,
  manager_user_id uuid NOT NULL,
  shopkeeper_name text NOT NULL,
  phone character varying NOT NULL,
  active boolean NOT NULL DEFAULT true,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT shopkeepers_pkey PRIMARY KEY (shopkeeper_id),
  CONSTRAINT shopkeepers_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(company_id),
  CONSTRAINT shopkeepers_manager_user_id_fkey FOREIGN KEY (manager_user_id) REFERENCES public.users(user_id),
  CONSTRAINT shopkeepers_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(user_id)
);
CREATE TABLE public.shopkeeper_payments (
  shopkeeper_payment_id uuid NOT NULL DEFAULT gen_random_uuid(),
  consumption_id uuid NOT NULL UNIQUE,
  shopkeeper_id uuid NOT NULL,
  company_id uuid NOT NULL,
  amount numeric NOT NULL CHECK (amount > 0::numeric),
  payment_status text NOT NULL CHECK (payment_status = ANY (ARRAY['PAID'::text, 'FAILED'::text])),
  provider_name text NOT NULL DEFAULT 'INTERNAL_TEST'::text,
  transaction_reference text,
  provider_response jsonb,
  paid_by uuid,
  paid_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT shopkeeper_payments_pkey PRIMARY KEY (shopkeeper_payment_id),
  CONSTRAINT shopkeeper_payments_consumption_id_fkey FOREIGN KEY (consumption_id) REFERENCES public.worker_consumptions(consumption_id),
  CONSTRAINT shopkeeper_payments_shopkeeper_id_fkey FOREIGN KEY (shopkeeper_id) REFERENCES public.shopkeepers(shopkeeper_id),
  CONSTRAINT shopkeeper_payments_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(company_id),
  CONSTRAINT shopkeeper_payments_paid_by_fkey FOREIGN KEY (paid_by) REFERENCES public.users(user_id)
);