import { useEffect, useMemo, useState } from 'react'
import api from '../api/api'
import { useAuth } from '../context/authStore'
import AppSidebar from './Appsidebar'

const today = new Date().toISOString().slice(0, 10)
const money = (value) => `${Number(value || 0).toLocaleString()} RWF`
const dateKey = (value) => String(value || '').slice(0, 10)
const weekStart = (value) => { const date = new Date(`${value}T00:00:00`); date.setDate(date.getDate() + (date.getDay() === 0 ? -6 : 1 - date.getDay())); return date.toISOString().slice(0, 10) }
const matchesPeriod = (row, period) => { const date = dateKey(row.work_date); return period === 'day' ? date === today : period === 'week' ? weekStart(date) === weekStart(today) : period === 'month' ? date.slice(0, 7) === today.slice(0, 7) : date.slice(0, 4) === today.slice(0, 4) }
const labelFor = (period) => period === 'day' ? 'Today' : period === 'week' ? `Week of ${weekStart(today)}` : period === 'month' ? new Date(`${today}T00:00:00`).toLocaleDateString(undefined, { month: 'long', year: 'numeric' }) : today.slice(0, 4)

export default function FlexibleWorkPage() {
  const { user } = useAuth()
  const [workers, setWorkers] = useState([]); const [rows, setRows] = useState([]); const [notice, setNotice] = useState('')
  const [selectedId, setSelectedId] = useState(''); const [period, setPeriod] = useState('day')
  const [form, setForm] = useState({ employee_id: '', work_date: today, agreed_daily_rate: '', work_details: '' })
  const total = (items) => items.reduce((sum, item) => sum + Number(item.agreed_daily_rate || 0), 0)
  const load = async () => { try { const [workerResult, workResult] = await Promise.all([api.get('/workers'), api.get('/flexible-work')]); const flexible = (workerResult.data?.data || []).filter((worker) => worker.payment_type === 'FLEXIBLE_DAILY'); setWorkers(flexible); setRows(workResult.data?.data || []); setSelectedId((id) => id || flexible[0]?.employee_id || '') } catch (error) { setNotice(error.response?.data?.message || 'Could not load flexible work.') } }
  useEffect(() => { load() }, [])
  const save = async (event) => { event.preventDefault(); try { await api.post('/flexible-work', form); setForm((current) => ({ ...current, employee_id: '', agreed_daily_rate: '', work_details: '' })); setNotice('Flexible work day recorded. It will be included in the biweekly payroll.'); load() } catch (error) { setNotice(error.response?.data?.message || 'Could not record flexible work.') } }
  const selected = workers.find((worker) => worker.employee_id === selectedId)
  const selectedRows = useMemo(() => rows.filter((row) => row.employee_id === selectedId && matchesPeriod(row, period)), [rows, selectedId, period])
  const totals = useMemo(() => ['day', 'week', 'month'].map((key) => ({ key, rows: rows.filter((row) => matchesPeriod(row, key)) })), [rows])
  return <div className="flex min-h-screen bg-slate-50"><AppSidebar /><main className="flex-1 p-4 md:p-8"><div className="mx-auto max-w-7xl space-y-6">
    <header className="rounded-2xl border bg-white p-6 shadow-sm"><p className="text-xs font-semibold uppercase text-blue-700">Variable daily pay</p><h1 className="mt-2 text-3xl font-bold">Flexible worker work ledger</h1><p className="mt-2 text-sm text-slate-600">Choose a worker card to view only that worker’s work, grouped by day, week, month, or year.</p></header>
    {notice && <p className="rounded-lg border border-blue-200 bg-blue-50 p-3 text-blue-900">{notice}</p>}
    <section className="grid gap-4 md:grid-cols-3">{totals.map((item) => <article key={item.key} className="rounded-2xl border border-blue-100 bg-white p-5 shadow-sm"><p className="text-xs font-bold uppercase tracking-wider text-blue-700">All flexible workers · {item.key === 'day' ? 'Today' : item.key === 'week' ? 'This week' : 'This month'}</p><p className="mt-3 text-3xl font-bold text-slate-900">{money(total(item.rows))}</p><p className="mt-2 text-sm text-slate-500">{item.rows.length} recorded work day{item.rows.length === 1 ? '' : 's'}</p></article>)}</section>
    {user?.role_name === 'ACCOUNTANT' && <form onSubmit={save} className="grid gap-3 rounded-2xl border bg-white p-6 shadow-sm md:grid-cols-2"><select required value={form.employee_id} onChange={(event) => setForm({ ...form, employee_id: event.target.value })} className="rounded-lg border p-3"><option value="">Select flexible worker</option>{workers.map((worker) => <option value={worker.employee_id} key={worker.employee_id}>{worker.employee_code} — {worker.first_name} {worker.last_name}</option>)}</select><input required type="date" value={form.work_date} onChange={(event) => setForm({ ...form, work_date: event.target.value })} className="rounded-lg border p-3"/><input required type="number" min="1" placeholder="Agreed rate for this day (RWF)" value={form.agreed_daily_rate} onChange={(event) => setForm({ ...form, agreed_daily_rate: event.target.value })} className="rounded-lg border p-3"/><input placeholder="Work details (optional)" value={form.work_details} onChange={(event) => setForm({ ...form, work_details: event.target.value })} className="rounded-lg border p-3"/><button className="rounded-lg bg-blue-600 p-3 font-semibold text-white md:col-span-2">Record worked day</button></form>}
    <section className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-wider text-blue-700">Worker cards</p><h2 className="mt-1 text-xl font-bold">Select one flexible worker</h2></div><button onClick={load} className="rounded-lg border border-blue-200 px-4 py-2 text-sm font-semibold text-blue-700 hover:bg-blue-50">Refresh</button></div><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{workers.map((worker) => { const workerRows = rows.filter((row) => row.employee_id === worker.employee_id); const active = worker.employee_id === selectedId; return <button key={worker.employee_id} onClick={() => setSelectedId(worker.employee_id)} className={`rounded-xl border p-4 text-left transition ${active ? 'border-blue-600 bg-blue-50 ring-2 ring-blue-100' : 'border-slate-200 bg-white hover:border-blue-300 hover:bg-blue-50/40'}`}><p className="font-bold text-slate-900">{worker.first_name} {worker.last_name}</p><p className="mt-1 text-xs text-slate-500">{worker.employee_code}</p><p className="mt-3 text-sm font-semibold text-blue-700">{money(total(workerRows))}</p><p className="mt-1 text-xs text-slate-500">{workerRows.length} recorded day{workerRows.length === 1 ? '' : 's'}</p></button> })}{!workers.length && <p className="text-sm text-slate-500">No flexible workers are registered in this manager scope.</p>}</div></section>
    {selected && <section className="overflow-hidden rounded-2xl border border-blue-200 bg-white shadow-sm"><div className="flex flex-col gap-3 border-b border-blue-100 bg-blue-50 p-5 md:flex-row md:items-center md:justify-between"><div><p className="text-xs font-bold uppercase tracking-wider text-blue-700">Selected worker</p><h2 className="mt-1 text-xl font-bold text-slate-900">{selected.first_name} {selected.last_name}</h2><p className="mt-1 text-sm text-slate-600">{selected.employee_code} · {labelFor(period)}</p></div><div className="flex flex-wrap gap-2">{['day', 'week', 'month', 'year'].map((key) => <button key={key} onClick={() => setPeriod(key)} className={`rounded-lg px-4 py-2 text-sm font-semibold ${period === key ? 'bg-blue-600 text-white' : 'border border-blue-200 bg-white text-blue-700 hover:bg-blue-100'}`}>{key === 'day' ? 'Today' : key === 'week' ? 'Weekly' : key === 'month' ? 'Monthly' : 'Yearly'}</button>)}</div></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-50 text-left text-xs uppercase text-slate-500"><tr><th className="p-4">Work date</th><th>Agreed daily rate</th><th>Work details</th><th>Payroll state</th></tr></thead><tbody>{selectedRows.map((row) => <tr className="border-t" key={row.flexible_work_id}><td className="p-4 font-medium">{row.work_date}</td><td className="font-semibold text-blue-700">{money(row.agreed_daily_rate)}</td><td>{row.work_details || '—'}</td><td>{row.payroll_id ? 'Included in payroll' : 'Awaiting payroll'}</td></tr>)}{!selectedRows.length && <tr><td colSpan="4" className="p-6 text-slate-500">No flexible work recorded for this {period === 'day' ? 'day' : period}.</td></tr>}</tbody><tfoot className="border-t-2 border-blue-200 bg-blue-50 font-bold text-blue-950"><tr><td className="p-4">{labelFor(period)} total</td><td>{money(total(selectedRows))}</td><td>{selectedRows.length} worked day{selectedRows.length === 1 ? '' : 's'}</td><td>—</td></tr></tfoot></table></div></section>}
  </div></main></div>
}
