import { useEffect, useState } from 'react'
import api from '../api/api'
import { useAuth } from '../context/authStore'
import { useOwnerManagerScope } from '../context/OwnerManagerScope'
import AppSidebar from './Appsidebar'
import OwnerManagerSelector from '../components/OwnerManagerSelector'

const money = (value) => `${Number(value || 0).toLocaleString()} RWF`
const emptyItem = () => ({ food_name: '', quantity: 1, unit: 'kg', unit_price: '' })
const emptySupply = () => ({ manager_user_id: '', supply_date: new Date().toISOString().slice(0, 10), notes: '', items: [emptyItem()] })
const total = (items) => items.reduce((sum, item) => sum + Number(item.quantity || 0) * Number(item.unit_price || 0), 0)

export default function FoodSupplyPage() {
  const { user } = useAuth(); const role = user?.role_name
  const { managerId, managers: ownerManagers } = useOwnerManagerScope()
  const [supplies, setSupplies] = useState([]); const [managers, setManagers] = useState([])
  const [supplier, setSupplier] = useState({ supplier_name: '', phone: '', email: '', username: '', password: '' })
  const [form, setForm] = useState(emptySupply); const [message, setMessage] = useState(''); const [saving, setSaving] = useState(false)
  const load = async () => { try { const response = await api.get('/food-supplies'); setSupplies(response.data?.data || []) } catch (error) { setMessage(error.response?.data?.message || 'Could not load food supplies.') } }
  useEffect(() => { load() }, [])
  useEffect(() => { if (role !== 'FOOD_SUPPLIER') return; api.get('/managers').then((response) => setManagers((response.data?.data || []).map((row) => ({ user_id: row.user_id, name: `${row.employees?.first_name || ''} ${row.employees?.last_name || ''}`.trim() || row.username })))).catch((error) => setMessage(error.response?.data?.message || 'Could not load managers.')) }, [role])
  const setItem = (index, field, value) => setForm((current) => ({ ...current, items: current.items.map((item, itemIndex) => itemIndex === index ? { ...item, [field]: value } : item) }))
  const submitSupply = async (event) => { event.preventDefault(); setSaving(true); try { await api.post('/food-supplies', form); setMessage('Food supply sent to the selected manager for verification.'); setForm(emptySupply()); await load() } catch (error) { setMessage(error.response?.data?.message || 'Could not save food supply.') } finally { setSaving(false) } }
  const submitSupplier = async (event) => { event.preventDefault(); setSaving(true); try { await api.post('/food-suppliers', supplier); setMessage(`Food supplier account created. Username: ${supplier.username}`); setSupplier({ supplier_name: '', phone: '', email: '', username: '', password: '' }) } catch (error) { setMessage(error.response?.data?.message || 'Could not create supplier.') } finally { setSaving(false) } }
  const act = async (id, action) => { const comments = action === 'request-changes' ? window.prompt('Reason for requested changes:') : ''; if (action === 'request-changes' && !comments) return; try { await api[action === 'pay' ? 'post' : 'put'](`/food-supplies/${id}/${action}`, action === 'pay' ? undefined : { comments }); setMessage(action === 'pay' ? 'Food supplier marked as paid.' : 'Food supply workflow updated.'); await load() } catch (error) { setMessage(error.response?.data?.message || 'Action failed.') } }
  const downloadReport = async () => { try { const response = await api.get('/food-supplies/report.csv', { responseType: 'blob' }); const link = document.createElement('a'); link.href = URL.createObjectURL(response.data); link.download = 'food-supply-report.csv'; link.click(); URL.revokeObjectURL(link.href) } catch (error) { setMessage(error.response?.data?.message || 'Could not download food report.') } }
  const visibleSupplies = role === 'OWNER' && managerId ? supplies.filter((supply) => supply.manager_user_id === managerId) : supplies
  const selectedName = managerId ? ownerManagers.find((manager) => manager.user_id === managerId)?.name || 'Selected manager' : 'All managers'
  const layout = ['OWNER', 'MANAGER', 'ACCOUNTANT', 'FOOD_SUPPLIER', 'SUPER_ADMIN'].includes(role)
  return <div className="flex min-h-screen bg-slate-50">{layout && <AppSidebar />}<main className="flex-1 p-6 lg:p-10"><div className="mx-auto max-w-7xl space-y-6">
    <header className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-3xl font-bold text-slate-900">Food Supply Control</h1><p className="mt-1 text-slate-600">Supplier → manager review → owner approval → owner payment.</p></div>{role === 'OWNER' && <OwnerManagerSelector />}</header>
    {role === 'OWNER' && <div className="rounded-xl border border-amber-100 bg-amber-50 p-3 text-sm text-amber-950"><strong>Viewing:</strong> {selectedName} · <strong>Supplies:</strong> {visibleSupplies.length} · <strong>Amount:</strong> {money(visibleSupplies.reduce((sum, supply) => sum + Number(supply.total_amount || 0), 0))}</div>}{message && <div className="rounded-xl border border-amber-200 bg-amber-50 p-3 text-amber-900">{message}</div>}
    {role === 'OWNER' && <form onSubmit={submitSupplier} className="rounded-2xl bg-white p-6 shadow-sm"><h2 className="text-xl font-semibold">Create the company food supplier account</h2><p className="mt-1 text-sm text-slate-500">One active supplier login per company. The supplier chooses a manager for every delivery.</p><div className="mt-4 grid gap-3 md:grid-cols-2">{Object.entries(supplier).map(([key, value]) => <input key={key} required={['supplier_name', 'username', 'password'].includes(key)} type={key === 'password' ? 'password' : 'text'} placeholder={key.replace('_', ' ')} value={value} onChange={(event) => setSupplier({ ...supplier, [key]: event.target.value })} className="rounded-lg border p-3" />)}</div><button disabled={saving} className="mt-4 rounded-lg bg-amber-500 px-5 py-2 font-semibold">Create supplier account</button></form>}
    {role === 'FOOD_SUPPLIER' && <form onSubmit={submitSupply} className="rounded-2xl bg-white p-6 shadow-sm"><h2 className="text-xl font-semibold">Record food supplied</h2><div className="mt-4 grid gap-3 md:grid-cols-3"><select required value={form.manager_user_id} onChange={(event) => setForm({ ...form, manager_user_id: event.target.value })} className="rounded-lg border p-3"><option value="">Select receiving manager</option>{managers.map((manager) => <option key={manager.user_id} value={manager.user_id}>{manager.name}</option>)}</select><input type="date" required value={form.supply_date} onChange={(event) => setForm({ ...form, supply_date: event.target.value })} className="rounded-lg border p-3" /><input placeholder="Notes / delivery reference" value={form.notes} onChange={(event) => setForm({ ...form, notes: event.target.value })} className="rounded-lg border p-3" /></div><div className="mt-4 space-y-2">{form.items.map((item, index) => <div key={index} className="grid gap-2 md:grid-cols-5"><input required placeholder="Food e.g. Tomatoes" value={item.food_name} onChange={(event) => setItem(index, 'food_name', event.target.value)} className="rounded-lg border p-3" /><input required type="number" min="0.01" step="0.01" value={item.quantity} onChange={(event) => setItem(index, 'quantity', event.target.value)} className="rounded-lg border p-3" /><input required placeholder="Unit (kg)" value={item.unit} onChange={(event) => setItem(index, 'unit', event.target.value)} className="rounded-lg border p-3" /><input required type="number" min="0" placeholder="Unit price" value={item.unit_price} onChange={(event) => setItem(index, 'unit_price', event.target.value)} className="rounded-lg border p-3" />{form.items.length > 1 ? <button type="button" onClick={() => setForm({ ...form, items: form.items.filter((_, itemIndex) => itemIndex !== index) })} className="rounded-lg bg-red-50 text-red-700">Remove</button> : <span />}</div>)}</div><div className="mt-4 flex flex-wrap items-center gap-3"><button type="button" onClick={() => setForm({ ...form, items: [...form.items, emptyItem()] })} className="rounded-lg border px-4 py-2">Add item</button><span className="font-semibold">Total: {money(total(form.items))}</span><button disabled={saving || !managers.length} className="rounded-lg bg-amber-500 px-5 py-2 font-semibold">Send to Manager</button></div></form>}
    <section className="overflow-hidden rounded-2xl bg-white shadow-sm"><div className="flex items-center justify-between border-b p-6"><div><h2 className="text-xl font-semibold">Food supply history</h2><p className="text-sm text-slate-500">The supplier sees final payment; managers see only their assigned deliveries.</p></div><button onClick={downloadReport} className="rounded-lg border px-4 py-2 text-sm font-semibold">Download report</button></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-50 text-left text-slate-500"><tr><th className="p-4">Date</th><th className="p-4">Supplier</th><th className="p-4">Items</th><th className="p-4">Total</th><th className="p-4">Status</th><th className="p-4">Action</th></tr></thead><tbody>{visibleSupplies.map((supply) => <tr key={supply.food_supply_id} className="border-t"><td className="p-4">{supply.supply_date}</td><td className="p-4">{supply.food_suppliers?.supplier_name}</td><td className="p-4">{(supply.food_supply_items || []).map((item) => `${item.food_name} ${item.quantity} ${item.unit}`).join(', ')}</td><td className="p-4 font-semibold">{money(supply.total_amount)}</td><td className="p-4">{supply.status} / {supply.payment_status}</td><td className="p-4 space-x-2">{role === 'MANAGER' && supply.status === 'PENDING_MANAGER' && <><button onClick={() => act(supply.food_supply_id, 'approve')} className="text-emerald-700">Verify</button><button onClick={() => act(supply.food_supply_id, 'request-changes')} className="text-red-700">Changes</button></>}{role === 'OWNER' && supply.status === 'PENDING_OWNER' && <><button onClick={() => act(supply.food_supply_id, 'approve')} className="text-emerald-700">Approve</button><button onClick={() => act(supply.food_supply_id, 'request-changes')} className="text-red-700">Changes</button></>}{role === 'OWNER' && supply.status === 'OWNER_APPROVED' && supply.payment_status !== 'PAID' && <button onClick={() => act(supply.food_supply_id, 'pay')} className="font-semibold text-amber-700">Pay</button>}</td></tr>)}{!visibleSupplies.length && <tr><td className="p-6 text-slate-500" colSpan="6">No food supply records in this scope.</td></tr>}</tbody></table></div></section>
  </div></main></div>
}
