import { useEffect, useState } from 'react'
import api from '../api/api'
import { useAuth } from '../context/authStore'
import AppSidebar from './Appsidebar'

const money = (value) => `${Number(value || 0).toLocaleString()} RWF`
const total = (items) => items.reduce((sum, item) => sum + Number(item.quantity || 0) * Number(item.unit_price || 0), 0)

export default function FoodSupplyPage() {
  const { user } = useAuth(); const role = user?.role_name
  const [supplies, setSupplies] = useState([]); const [message, setMessage] = useState(''); const [saving, setSaving] = useState(false)
  const [supplier, setSupplier] = useState({ supplier_name: '', phone: '', email: '', username: '', password: '' })
  const [form, setForm] = useState({ supply_date: new Date().toISOString().slice(0,10), notes: '', items: [{ food_name: '', quantity: 1, unit: 'kg', unit_price: '' }] })
  const load = async () => { try { const r = await api.get('/food-supplies'); setSupplies(r.data?.data || []) } catch (e) { setMessage(e.response?.data?.message || 'Could not load food supplies.') } }
  useEffect(() => { load() }, [])
  const submitSupply = async (e) => { e.preventDefault(); setSaving(true); try { await api.post('/food-supplies', form); setMessage('Food supply sent to the manager for verification.'); setForm({ supply_date: new Date().toISOString().slice(0,10), notes:'',items:[{food_name:'',quantity:1,unit:'kg',unit_price:''}] }); load() } catch(e){setMessage(e.response?.data?.message || 'Could not save food supply.')} finally {setSaving(false)} }
  const submitSupplier = async (e) => { e.preventDefault(); setSaving(true); try { await api.post('/food-suppliers', supplier); setMessage(`Food Supplier account created. Username: ${supplier.username}`); setSupplier({supplier_name:'',phone:'',email:'',username:'',password:''}) } catch(e){setMessage(e.response?.data?.message || 'Could not create supplier.')} finally {setSaving(false)} }
  const act = async (id, action) => { const comments = action === 'request-changes' ? window.prompt('Reason for requested changes:') : ''; if (action === 'request-changes' && !comments) return; try { await api[action === 'pay' ? 'post' : 'put'](`/food-supplies/${id}/${action}`, action === 'pay' ? undefined : { comments }); setMessage(action === 'pay' ? 'Food supply paid with INTERNAL_TEST provider.' : 'Food supply workflow updated.'); load() } catch(e){setMessage(e.response?.data?.message || 'Action failed.')} }
  const downloadReport = async () => { try { const response = await api.get('/food-supplies/report.csv', { responseType: 'blob' }); const link = document.createElement('a'); link.href = URL.createObjectURL(response.data); link.download = 'food-supply-report.csv'; link.click(); URL.revokeObjectURL(link.href); } catch (e) { setMessage(e.response?.data?.message || 'Could not download food report.') } }
  const layout = ['OWNER','MANAGER','FOOD_SUPPLIER','SUPER_ADMIN'].includes(role)
  return <div className="flex min-h-screen bg-slate-50">{layout && <AppSidebar/>}<main className="flex-1 p-6 lg:p-10"><div className="mx-auto max-w-7xl space-y-6"><header><h1 className="text-3xl font-bold text-slate-900">Food Supply Control</h1><p className="mt-1 text-slate-600">Every supply is itemized, verified by the manager, approved and paid once by the owner.</p></header>{message && <div className="rounded-xl border border-amber-200 bg-amber-50 p-3 text-amber-900">{message}</div>}
  {role === 'FOOD_SUPPLIER' && <form onSubmit={submitSupply} className="rounded-2xl bg-white p-6 shadow-sm"><h2 className="text-xl font-semibold">Record food supplied</h2><div className="mt-4 grid gap-3 md:grid-cols-2"><input type="date" required value={form.supply_date} onChange={e=>setForm({...form,supply_date:e.target.value})} className="rounded-lg border p-3"/><input placeholder="Notes / delivery reference" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} className="rounded-lg border p-3"/></div><div className="mt-4 space-y-2">{form.items.map((item,index)=><div key={index} className="grid gap-2 md:grid-cols-5"><input required placeholder="Food e.g. Tomatoes" value={item.food_name} onChange={e=>{const items=[...form.items];items[index]={...item,food_name:e.target.value};setForm({...form,items})}} className="rounded-lg border p-3"/><input required type="number" min="0.01" step="0.01" value={item.quantity} onChange={e=>{const items=[...form.items];items[index]={...item,quantity:e.target.value};setForm({...form,items})}} className="rounded-lg border p-3"/><input required placeholder="Unit (kg)" value={item.unit} onChange={e=>{const items=[...form.items];items[index]={...item,unit:e.target.value};setForm({...form,items})}} className="rounded-lg border p-3"/><input required type="number" min="0" placeholder="Unit price" value={item.unit_price} onChange={e=>{const items=[...form.items];items[index]={...item,unit_price:e.target.value};setForm({...form,items})}} className="rounded-lg border p-3"/>{form.items.length>1?<button type="button" onClick={()=>setForm({...form,items:form.items.filter((_,i)=>i!==index)})} className="rounded-lg bg-red-50 text-red-700">Remove</button>:<span/>}</div>)}</div><div className="mt-4 flex flex-wrap items-center gap-3"><button type="button" onClick={()=>setForm({...form,items:[...form.items,{food_name:'',quantity:1,unit:'kg',unit_price:''}]})} className="rounded-lg border px-4 py-2">Add item</button><span className="font-semibold">Total: {money(total(form.items))}</span><button disabled={saving} className="rounded-lg bg-amber-500 px-5 py-2 font-semibold">Send to Manager</button></div></form>}
  {role === 'MANAGER' && <form onSubmit={submitSupplier} className="rounded-2xl bg-white p-6 shadow-sm"><h2 className="text-xl font-semibold">Create Food Supplier account</h2><p className="mt-1 text-sm text-slate-500">Give these credentials to the supplier after creating the account.</p><div className="mt-4 grid gap-3 md:grid-cols-2">{Object.entries(supplier).map(([key,value])=><input key={key} required={['supplier_name','username','password'].includes(key)} type={key==='password'?'password':'text'} placeholder={key.replace('_',' ')} value={value} onChange={e=>setSupplier({...supplier,[key]:e.target.value})} className="rounded-lg border p-3"/>)}</div><button disabled={saving} className="mt-4 rounded-lg bg-amber-500 px-5 py-2 font-semibold">Create supplier</button></form>}
  <section className="overflow-hidden rounded-2xl bg-white shadow-sm"><div className="flex items-center justify-between border-b p-6"><div><h2 className="text-xl font-semibold">Food supply history</h2><p className="text-sm text-slate-500">Totals are calculated from the listed food items.</p></div><button onClick={downloadReport} className="rounded-lg border px-4 py-2 text-sm font-semibold">Download food report</button></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-50 text-left text-slate-500"><tr><th className="p-4">Date</th><th className="p-4">Supplier</th><th className="p-4">Items</th><th className="p-4">Total</th><th className="p-4">Status</th><th className="p-4">Action</th></tr></thead><tbody>{supplies.map(s=><tr key={s.food_supply_id} className="border-t"><td className="p-4">{s.supply_date}</td><td className="p-4">{s.food_suppliers?.supplier_name}</td><td className="p-4">{(s.food_supply_items||[]).map(i=>`${i.food_name} ${i.quantity} ${i.unit}`).join(', ')}</td><td className="p-4 font-semibold">{money(s.total_amount)}</td><td className="p-4">{s.status} / {s.payment_status}</td><td className="p-4 space-x-2">{role==='MANAGER'&&s.status==='PENDING_MANAGER'&&<><button onClick={()=>act(s.food_supply_id,'approve')} className="text-emerald-700">Verify</button><button onClick={()=>act(s.food_supply_id,'request-changes')} className="text-red-700">Changes</button></>}{role==='OWNER'&&s.status==='PENDING_OWNER'&&<><button onClick={()=>act(s.food_supply_id,'approve')} className="text-emerald-700">Approve</button><button onClick={()=>act(s.food_supply_id,'request-changes')} className="text-red-700">Changes</button></>}{role==='OWNER'&&s.status==='OWNER_APPROVED'&&s.payment_status!=='PAID'&&<button onClick={()=>act(s.food_supply_id,'pay')} className="font-semibold text-amber-700">Pay (INTERNAL_TEST)</button>}</td></tr>)}{!supplies.length&&<tr><td className="p-6 text-slate-500" colSpan="6">No food supply records yet.</td></tr>}</tbody></table></div></section></div></main></div>
}
