import { useMemo, useState } from 'react'
import { ArrowRight, FileText, Search, UserRound, Wallet } from 'lucide-react'
import api from '../api/api'
import AppSidebar from './Appsidebar'
import { useAuth } from '../context/authStore'
import { useOwnerManagerScope } from '../context/OwnerManagerScope'
import OwnerManagerSelector from '../components/OwnerManagerSelector'

const money = (value) => `${Number(value || 0).toLocaleString()} RWF`
const nameOf = (employee) => `${employee?.first_name || ''} ${employee?.last_name || ''}`.trim()
const statusTone = (value) => String(value || '').startsWith('FAILED') ? 'bg-red-100 text-red-800' : value === 'PAID' ? 'bg-emerald-100 text-emerald-800' : 'bg-blue-100 text-blue-800'

export default function GlobalSearchPage() {
  const { user } = useAuth(); const { managerId } = useOwnerManagerScope()
  const [query, setQuery] = useState(''); const [data, setData] = useState(null); const [loading, setLoading] = useState(false); const [message, setMessage] = useState('')
  const search = async (event) => { event?.preventDefault(); if (query.trim().length < 2) return setMessage('Enter at least two letters, a worker code, ID, or MoMo number.'); setLoading(true); setMessage(''); try { const response = await api.get('/search', { params: { q: query, manager_user_id: user?.role_name === 'OWNER' ? managerId || undefined : undefined } }); setData(response.data?.data || {}); } catch (error) { setMessage(error.response?.data?.message || 'Search could not be completed.'); } finally { setLoading(false); } }
  const total = useMemo(() => Object.values(data || {}).reduce((sum, rows) => sum + (rows?.length || 0), 0), [data])
  return <div className="flex min-h-screen bg-slate-50"><AppSidebar/><main className="min-w-0 flex-1 p-4 md:p-8"><div className="mx-auto max-w-7xl space-y-6"><header className="flex flex-wrap items-end justify-between gap-4 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div><p className="text-xs font-bold uppercase tracking-wider text-blue-700">Company search</p><h1 className="mt-2 text-3xl font-bold text-slate-900">Find worker payment information</h1><p className="mt-2 text-sm text-slate-600">Search a worker name, code, national ID, or MoMo number. Results include only data you are allowed to see.</p></div>{user?.role_name === 'OWNER' && <OwnerManagerSelector/>}</header><form onSubmit={search} className="flex gap-2 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><label className="relative flex-1"><Search className="pointer-events-none absolute left-4 top-3.5 text-slate-400" size={20}/><input autoFocus value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Worker name, worker code, national ID, or MTN MoMo number" className="w-full rounded-xl border border-slate-300 py-3 pl-11 pr-4 outline-none focus:border-blue-500"/></label><button disabled={loading} className="rounded-xl bg-blue-600 px-5 font-bold text-white hover:bg-blue-700 disabled:opacity-60">{loading ? 'Searching…' : 'Search'}</button></form>{message && <div className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-800">{message}</div>}{data && <p className="text-sm font-medium text-slate-600">{total} matching record(s) in your current scope.</p>}<div className="grid gap-5 xl:grid-cols-2"><Workers rows={data?.workers || []}/><Payroll rows={data?.payroll || []}/><Advances rows={data?.advances || []}/><Payments rows={data?.payments || []}/><Flexible rows={data?.flexible_work || []}/></div></div></main></div>
}
function Section({ title, icon: Icon, children, empty }) { return <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><header className="flex items-center gap-2 border-b border-slate-100 p-5"><Icon className="text-blue-600" size={19}/><h2 className="font-bold text-slate-900">{title}</h2></header>{empty ? <p className="p-5 text-sm text-slate-500">No matching {title.toLowerCase()} found.</p> : <div className="overflow-x-auto">{children}</div>}</section> }
function Workers({ rows }) { return <Section title="Workers" icon={UserRound} empty={!rows.length}><table className="w-full min-w-[560px] text-sm"><thead><tr className="bg-slate-50 text-left text-slate-600"><th className="p-3">Worker</th><th>Code</th><th>MoMo</th><th>Type</th><th>Status</th></tr></thead><tbody>{rows.map((r) => <tr className="border-t" key={r.employee_id}><td className="p-3 font-semibold">{nameOf(r)}</td><td>{r.employee_code}</td><td>{r.phone}</td><td>{r.payment_type === 'FLEXIBLE_DAILY' ? 'Flexible daily' : 'Fixed daily'}</td><td><span className={`rounded-full px-2 py-1 text-xs font-bold ${statusTone(r.status)}`}>{r.status}</span></td></tr>)}</tbody></table></Section> }
function Payroll({ rows }) { return <Section title="Payroll" icon={Wallet} empty={!rows.length}><table className="w-full min-w-[560px] text-sm"><thead><tr className="bg-slate-50 text-left text-slate-600"><th className="p-3">Worker</th><th>Period</th><th>Net salary</th><th>Payment</th></tr></thead><tbody>{rows.map((r) => <tr className="border-t" key={r.payroll_id}><td className="p-3 font-semibold">{nameOf(r.employees)}</td><td>{r.payroll_period_start || '—'} to {r.payroll_period_end || '—'}</td><td>{money(r.net_salary)}</td><td><span className={`rounded-full px-2 py-1 text-xs font-bold ${statusTone(r.payment_status)}`}>{r.payment_status}</span></td></tr>)}</tbody></table></Section> }
function Advances({ rows }) { return <Section title="Advances" icon={Wallet} empty={!rows.length}><table className="w-full min-w-[560px] text-sm"><thead><tr className="bg-slate-50 text-left text-slate-600"><th className="p-3">Worker</th><th>Date</th><th>Amount</th><th>Status</th></tr></thead><tbody>{rows.map((r) => <tr className="border-t" key={r.advance_id}><td className="p-3 font-semibold">{nameOf(r.employees)}</td><td>{r.request_date}</td><td>{money(r.amount)}</td><td><span className={`rounded-full px-2 py-1 text-xs font-bold ${statusTone(r.payment_status || r.status)}`}>{r.payment_status || r.status}</span></td></tr>)}</tbody></table></Section> }
function Payments({ rows }) { return <Section title="Payment proof" icon={FileText} empty={!rows.length}><table className="w-full min-w-[620px] text-sm"><thead><tr className="bg-slate-50 text-left text-slate-600"><th className="p-3">Worker</th><th>Date</th><th>Amount</th><th>Status / reason</th></tr></thead><tbody>{rows.map((r) => <tr className="border-t" key={r.payment_id}><td className="p-3 font-semibold">{nameOf(r.employees)}</td><td>{r.payment_date || '—'}</td><td>{money(r.amount)}</td><td><span className={`rounded-full px-2 py-1 text-xs font-bold ${statusTone(r.payment_status)}`}>{r.payment_status}</span>{r.failure_reason && <p className="mt-1 text-xs text-red-700">{r.failure_reason}</p>}</td></tr>)}</tbody></table></Section> }
function Flexible({ rows }) { return <Section title="Flexible work entries" icon={ArrowRight} empty={!rows.length}><table className="w-full min-w-[560px] text-sm"><thead><tr className="bg-slate-50 text-left text-slate-600"><th className="p-3">Worker</th><th>Work date</th><th>Agreed daily amount</th></tr></thead><tbody>{rows.map((r) => <tr className="border-t" key={r.flexible_work_id}><td className="p-3 font-semibold">{nameOf(r.employees)}</td><td>{r.work_date}</td><td>{money(r.agreed_daily_rate)}</td></tr>)}</tbody></table></Section> }
