import { useMemo, useState } from 'react'
import { ArrowRight, FileText, Search, UserRound, Wallet } from 'lucide-react'
import api from '../api/api'
import AppSidebar from './Appsidebar'
import { useAuth } from '../context/authStore'
import { useOwnerManagerScope } from '../context/OwnerManagerScope'
import { useLanguage } from '../context/LanguageContext'
import OwnerManagerSelector from '../components/OwnerManagerSelector'

const money = (value) => `${Number(value || 0).toLocaleString()} RWF`
const nameOf = (employee) => `${employee?.first_name || ''} ${employee?.last_name || ''}`.trim()
const statusTone = (value) => String(value || '').startsWith('FAILED') ? 'bg-red-100 text-red-800' : value === 'PAID' ? 'bg-emerald-100 text-emerald-800' : 'bg-blue-100 text-blue-800'

export default function GlobalSearchPage() {
  const { user } = useAuth(); const { managerId } = useOwnerManagerScope(); const { t } = useLanguage()
  const [query, setQuery] = useState(''); const [data, setData] = useState(null); const [loading, setLoading] = useState(false); const [message, setMessage] = useState('')
  const search = async (event) => { event?.preventDefault(); if (query.trim().length < 2) return setMessage(t('searchPage.minimum')); setLoading(true); setMessage(''); try { const response = await api.get('/search', { params: { q: query, manager_user_id: user?.role_name === 'OWNER' ? managerId || undefined : undefined } }); setData(response.data?.data || {}); } catch (error) { setMessage(error.response?.data?.message || t('searchPage.failed')); } finally { setLoading(false); } }
  const total = useMemo(() => Object.values(data || {}).reduce((sum, rows) => sum + (rows?.length || 0), 0), [data])
  return <div className="flex min-h-screen bg-slate-50"><AppSidebar/><main className="min-w-0 flex-1 p-4 md:p-8"><div className="mx-auto max-w-7xl space-y-6"><header className="flex flex-wrap items-end justify-between gap-4 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div><p className="text-xs font-bold uppercase tracking-wider text-blue-700">{t('searchPage.eyebrow')}</p><h1 className="mt-2 text-3xl font-bold text-slate-900">{t('searchPage.title')}</h1><p className="mt-2 text-sm text-slate-600">{t('searchPage.description')}</p></div>{user?.role_name === 'OWNER' && <OwnerManagerSelector/>}</header><form onSubmit={search} className="flex gap-2 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><label className="relative flex-1"><Search className="pointer-events-none absolute left-4 top-3.5 text-slate-400" size={20}/><input autoFocus value={query} onChange={(event) => setQuery(event.target.value)} placeholder={t('searchPage.input')} className="w-full rounded-xl border border-slate-300 py-3 pl-11 pr-4 outline-none focus:border-blue-500"/></label><button disabled={loading} className="rounded-xl bg-blue-600 px-5 font-bold text-white hover:bg-blue-700 disabled:opacity-60">{loading ? t('searchPage.searching') : t('common.search')}</button></form>{message && <div className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-800">{message}</div>}{data && <p className="text-sm font-medium text-slate-600">{t('searchPage.matches', { count: total })}</p>}<div className="grid gap-5 xl:grid-cols-2"><Workers rows={data?.workers || []}/><Payroll rows={data?.payroll || []}/><Advances rows={data?.advances || []}/><Payments rows={data?.payments || []}/><Flexible rows={data?.flexible_work || []}/></div></div></main></div>
}
function Section({ title, icon: Icon, children, empty }) { const { t } = useLanguage(); return <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><header className="flex items-center gap-2 border-b border-slate-100 p-5"><Icon className="text-blue-600" size={19}/><h2 className="font-bold text-slate-900">{title}</h2></header>{empty ? <p className="p-5 text-sm text-slate-500">{t('searchPage.noMatches', { section: title.toLowerCase() })}</p> : <div className="overflow-x-auto">{children}</div>}</section> }
function Workers({ rows }) { const { t } = useLanguage(); return <Section title={t('workers.title')} icon={UserRound} empty={!rows.length}><table className="w-full min-w-[560px] text-sm"><thead><tr className="bg-slate-50 text-left text-slate-600"><th className="p-3">{t('workers.worker')}</th><th>{t('searchPage.code')}</th><th>{t('searchPage.momo')}</th><th>{t('searchPage.type')}</th><th>{t('common.status')}</th></tr></thead><tbody>{rows.map((r) => <tr className="border-t" key={r.employee_id}><td className="p-3 font-semibold">{nameOf(r)}</td><td>{r.employee_code}</td><td>{r.phone}</td><td>{r.payment_type === 'FLEXIBLE_DAILY' ? t('searchPage.flexible') : t('searchPage.fixed')}</td><td><span className={`rounded-full px-2 py-1 text-xs font-bold ${statusTone(r.status)}`}>{r.status}</span></td></tr>)}</tbody></table></Section> }
function Payroll({ rows }) { const { t } = useLanguage(); return <Section title={t('payroll.title')} icon={Wallet} empty={!rows.length}><table className="w-full min-w-[560px] text-sm"><thead><tr className="bg-slate-50 text-left text-slate-600"><th className="p-3">{t('workers.worker')}</th><th>{t('payroll.period')}</th><th>{t('searchPage.netSalary')}</th><th>{t('payments.title')}</th></tr></thead><tbody>{rows.map((r) => <tr className="border-t" key={r.payroll_id}><td className="p-3 font-semibold">{nameOf(r.employees)}</td><td>{r.payroll_period_start || '—'} {t('food.to')} {r.payroll_period_end || '—'}</td><td>{money(r.net_salary)}</td><td><span className={`rounded-full px-2 py-1 text-xs font-bold ${statusTone(r.payment_status)}`}>{r.payment_status}</span></td></tr>)}</tbody></table></Section> }
function Advances({ rows }) { const { t } = useLanguage(); return <Section title={t('navigation.advances')} icon={Wallet} empty={!rows.length}><table className="w-full min-w-[560px] text-sm"><thead><tr className="bg-slate-50 text-left text-slate-600"><th className="p-3">{t('workers.worker')}</th><th>{t('common.date')}</th><th>{t('common.amount')}</th><th>{t('common.status')}</th></tr></thead><tbody>{rows.map((r) => <tr className="border-t" key={r.advance_id}><td className="p-3 font-semibold">{nameOf(r.employees)}</td><td>{r.request_date}</td><td>{money(r.amount)}</td><td><span className={`rounded-full px-2 py-1 text-xs font-bold ${statusTone(r.payment_status || r.status)}`}>{r.payment_status || r.status}</span></td></tr>)}</tbody></table></Section> }
function Payments({ rows }) { const { t } = useLanguage(); return <Section title={t('searchPage.paymentProof')} icon={FileText} empty={!rows.length}><table className="w-full min-w-[620px] text-sm"><thead><tr className="bg-slate-50 text-left text-slate-600"><th className="p-3">{t('workers.worker')}</th><th>{t('common.date')}</th><th>{t('common.amount')}</th><th>{t('searchPage.statusReason')}</th></tr></thead><tbody>{rows.map((r) => <tr className="border-t" key={r.payment_id}><td className="p-3 font-semibold">{nameOf(r.employees)}</td><td>{r.payment_date || '—'}</td><td>{money(r.amount)}</td><td><span className={`rounded-full px-2 py-1 text-xs font-bold ${statusTone(r.payment_status)}`}>{r.payment_status}</span>{r.failure_reason && <p className="mt-1 text-xs text-red-700">{r.failure_reason}</p>}</td></tr>)}</tbody></table></Section> }
function Flexible({ rows }) { const { t } = useLanguage(); return <Section title={t('searchPage.flexibleEntries')} icon={ArrowRight} empty={!rows.length}><table className="w-full min-w-[560px] text-sm"><thead><tr className="bg-slate-50 text-left text-slate-600"><th className="p-3">{t('workers.worker')}</th><th>{t('searchPage.workDate')}</th><th>{t('searchPage.agreedAmount')}</th></tr></thead><tbody>{rows.map((r) => <tr className="border-t" key={r.flexible_work_id}><td className="p-3 font-semibold">{nameOf(r.employees)}</td><td>{r.work_date}</td><td>{money(r.agreed_daily_rate)}</td></tr>)}</tbody></table></Section> }
