import { useEffect, useMemo, useState } from 'react';
import api from '../api/api';
import { useAuth } from '../context/authStore';
import AppSidebar from './Appsidebar';

const today = () => new Date().toISOString().slice(0, 10);
const money = (value) => `${Number(value || 0).toLocaleString()} RWF`;
const currentPeriod = () => { const date = new Date(); return { month: date.getMonth() + 1, year: date.getFullYear() }; };

export default function MonthlyStaffPage() {
  const { user } = useAuth();
  const owner = user?.role_name === 'OWNER';
  const [rows, setRows] = useState([]); const [message, setMessage] = useState('');
  const [period, setPeriod] = useState(currentPeriod);
  const [form, setForm] = useState({ staff_type: 'SECURITY', full_name: '', national_id: '', momo_phone: '', monthly_salary: '', start_date: today() });

  const load = async () => { try { const response = await api.get('/monthly-staff'); setRows(response.data?.data || []); } catch (error) { setMessage(error.response?.data?.message || 'Could not load monthly staff.'); } };
  useEffect(() => { load(); }, []);

  const create = async (event) => { event.preventDefault(); try { await api.post('/monthly-staff', form); setForm({ ...form, full_name: '', national_id: '', momo_phone: '', monthly_salary: '' }); setMessage('Monthly worker saved. Daily salary is monthly salary ÷ 30.'); load(); } catch (error) { setMessage(error.response?.data?.message || 'Could not save monthly worker.'); } };
  const generate = async (staff) => { try { const response = await api.post(`/monthly-staff/${staff.monthly_staff_id}/payroll`, period); setMessage(`Monthly payroll is ready: ${money(response.data?.data?.net_salary)}. It remains unpaid until the Owner pays it.`); load(); } catch (error) { setMessage(error.response?.data?.message || 'Could not generate monthly payroll.'); } };
  const pay = async (payroll) => { if (!window.confirm(`Pay ${money(payroll.net_salary)} to this monthly worker?`)) return; try { await api.post(`/monthly-staff/payroll/${payroll.monthly_staff_payroll_id}/pay`); setMessage('Monthly payment completed and tracked.'); load(); } catch (error) { setMessage(error.response?.data?.message || 'Payment failed.'); } };
  const advance = async (staff) => { const amount = window.prompt(`Advance for ${staff.full_name}; maximum ${money(Number(staff.monthly_salary) / 2)}.`); const reason = amount && window.prompt('Reason for advance:'); if (!reason) return; try { await api.post(`/monthly-staff/${staff.monthly_staff_id}/advances`, { amount, reason }); setMessage('Advance is ready for Owner payment.'); load(); } catch (error) { setMessage(error.response?.data?.message || 'Advance is not available yet.'); } };
  const payAdvance = async (record) => { if (!window.confirm(`Pay advance of ${money(record.amount)}?`)) return; try { await api.post(`/monthly-staff/advances/${record.monthly_staff_advance_id}/pay`); setMessage('Advance paid and recorded.'); load(); } catch (error) { setMessage(error.response?.data?.message || 'Advance payment failed.'); } };

  const totals = useMemo(() => rows.reduce((all, staff) => {
    const payrolls = staff.monthly_staff_payroll || []; const selected = payrolls.find((item) => Number(item.payroll_month) === Number(period.month) && Number(item.payroll_year) === Number(period.year));
    all.staff += 1; all.gross += Number(selected?.gross_salary || 0); all.net += Number(selected?.net_salary || 0); if (selected && selected.payment_status !== 'PAID') { all.unpaid += Number(selected.net_salary || 0); all.unpaidCount += 1; } return all;
  }, { staff: 0, gross: 0, net: 0, unpaid: 0, unpaidCount: 0 }), [rows, period]);

  return <div className="flex min-h-screen bg-slate-50"><AppSidebar /><main className="min-w-0 flex-1 p-4 md:p-8"><div className="mx-auto max-w-7xl space-y-6">
    <header className="rounded-2xl border border-blue-100 bg-white p-6 shadow-sm"><p className="text-xs font-bold uppercase tracking-wider text-blue-700">Monthly worker payroll</p><h1 className="mt-2 text-3xl font-bold text-slate-900">Monthly staff and private workers</h1><p className="mt-2 text-sm text-slate-600">{owner ? 'Owner can pay monthly payroll and see confidential private staff. Managers can add and prepare only their Accountant/Security monthly workers.' : 'Add your Accountant or Security monthly workers and prepare their monthly payroll. Only the Owner can pay it.'}</p></header>
    {message && <p className="rounded-xl border border-blue-200 bg-blue-50 p-4 text-sm text-blue-950">{message}</p>}
    <section className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-bold uppercase text-blue-700">Selected payroll month</p><h2 className="mt-1 text-xl font-bold">Monthly totals and unpaid money</h2></div><div className="flex gap-2"><select value={period.month} onChange={(event) => setPeriod({ ...period, month: Number(event.target.value) })} className="rounded-lg border p-2">{Array.from({ length: 12 }, (_, index) => <option key={index + 1} value={index + 1}>{new Date(2026, index, 1).toLocaleString(undefined, { month: 'long' })}</option>)}</select><input type="number" min="2020" value={period.year} onChange={(event) => setPeriod({ ...period, year: Number(event.target.value) })} className="w-24 rounded-lg border p-2" /></div></div><div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><TotalCard label="Monthly workers" value={totals.staff} /><TotalCard label="Gross salary generated" value={money(totals.gross)} /><TotalCard label="Net salary generated" value={money(totals.net)} /><TotalCard label="Unpaid now" value={money(totals.unpaid)} red /><TotalCard label="Unpaid payroll records" value={totals.unpaidCount} red /></div></section>
    <form onSubmit={create} className="grid gap-3 rounded-2xl border bg-white p-6 shadow-sm md:grid-cols-3"><select value={form.staff_type} onChange={(event) => setForm({ ...form, staff_type: event.target.value })} className="rounded-lg border p-3"><option value="ACCOUNTANT">Accountant</option><option value="SECURITY">Security</option>{owner && <option value="OWNER_PRIVATE">Owner-private worker</option>}</select><input required placeholder="Full name" value={form.full_name} onChange={(event) => setForm({ ...form, full_name: event.target.value })} className="rounded-lg border p-3"/><input placeholder="National ID" value={form.national_id} onChange={(event) => setForm({ ...form, national_id: event.target.value })} className="rounded-lg border p-3"/><input required placeholder="MTN number" value={form.momo_phone} onChange={(event) => setForm({ ...form, momo_phone: event.target.value })} className="rounded-lg border p-3"/><input required min="1" type="number" placeholder="Monthly salary (RWF)" value={form.monthly_salary} onChange={(event) => setForm({ ...form, monthly_salary: event.target.value })} className="rounded-lg border p-3"/><input required type="date" value={form.start_date} onChange={(event) => setForm({ ...form, start_date: event.target.value })} className="rounded-lg border p-3"/><button className="rounded-lg bg-blue-600 p-3 font-bold text-white md:col-span-3">Add monthly worker</button></form>
    <section className="overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="border-b p-5"><h2 className="text-xl font-bold">Monthly payroll register</h2><p className="mt-1 text-sm text-slate-600">A generated month can stay unpaid. It is still shown as unpaid until Owner pays it; generating another month never hides it.</p></div><div className="overflow-x-auto"><table className="min-w-[1100px] w-full text-sm"><thead className="bg-slate-50 text-left"><tr><th className="p-4">Staff</th><th>Salary</th><th>Selected month</th><th>All unpaid months</th><th>Advances</th><th className="p-4">Actions</th></tr></thead><tbody>{rows.map((staff) => { const payrolls = staff.monthly_staff_payroll || []; const selected = payrolls.find((item) => Number(item.payroll_month) === Number(period.month) && Number(item.payroll_year) === Number(period.year)); const unpaid = payrolls.filter((item) => item.payment_status !== 'PAID'); return <tr className="border-t" key={staff.monthly_staff_id}><td className="p-4 font-bold text-slate-900">{staff.full_name}<br/><span className="font-normal text-slate-500">{staff.staff_type} · {staff.momo_phone}</span></td><td>{money(staff.monthly_salary)}<br/><span className="text-slate-500">{money(staff.daily_salary)} / day</span></td><td>{selected ? <><b>{money(selected.net_salary)}</b><br/><span className={selected.payment_status === 'PAID' ? 'text-emerald-700' : 'font-bold text-red-700'}>{selected.payment_status}</span></> : <span className="text-slate-500">Not generated</span>}</td><td>{unpaid.length ? unpaid.map((item) => <div key={item.monthly_staff_payroll_id} className="mb-1 text-red-700">{item.payroll_month}/{item.payroll_year}: {money(item.net_salary)} · {item.payment_status}{owner && <button onClick={() => pay(item)} className="ml-2 font-bold text-blue-700">Pay</button>}</div>) : <span className="text-emerald-700">None</span>}</td><td>{(staff.monthly_staff_advances || []).map((item) => <div key={item.monthly_staff_advance_id}>{money(item.amount)} · {item.status}{owner && item.status === 'OWNER_APPROVED' && <button onClick={() => payAdvance(item)} className="ml-2 font-bold text-blue-700">Pay advance</button>}</div>) || '—'}</td><td className="p-4">{owner && staff.staff_type !== 'OWNER_PRIVATE' && <button onClick={() => advance(staff)} className="mr-3 font-bold text-amber-700">Advance after day 15</button>}{!selected && <button onClick={() => generate(staff)} className="font-bold text-emerald-700">Generate {period.month}/{period.year}</button>}{owner && selected && selected.payment_status !== 'PAID' && <button onClick={() => pay(selected)} className="ml-3 font-bold text-blue-700">Pay selected month</button>}</td></tr>; })}{!rows.length && <tr><td colSpan="6" className="p-8 text-center text-slate-500">No monthly workers in this scope yet.</td></tr>}</tbody></table></div></section>
  </div></main></div>;
}
function TotalCard({ label, value, red = false }) { return <article className="rounded-xl border border-slate-200 bg-white p-4"><p className="text-xs font-bold uppercase tracking-wide text-slate-600">{label}</p><p className={`mt-2 text-xl font-bold ${red ? 'text-red-700' : 'text-slate-900'}`}>{value}</p></article>; }
