import { useEffect, useMemo, useState } from 'react'
import api from '../api/api'
import { useAuth } from '../context/authStore'
import { useOwnerManagerScope } from '../context/OwnerManagerScope'
import OwnerManagerSelector from '../components/OwnerManagerSelector'
import AppSidebar from './Appsidebar'

const money = (value) => `${Number(value || 0).toLocaleString()} RWF`
const badge = (value) => value === 'PAID' ? 'bg-emerald-100 text-emerald-800' : value === 'FAILED' || value === 'CHANGES_REQUESTED' ? 'bg-red-100 text-red-800' : value === 'OWNER_APPROVED' || value === 'PENDING_OWNER' ? 'bg-blue-100 text-blue-800' : 'bg-amber-100 text-amber-800'

export default function OperationalExpensesPage() {
  const { user } = useAuth(); const role = user?.role_name; const { managerId } = useOwnerManagerScope()
  const [rows, setRows] = useState([]); const [message, setMessage] = useState(''); const [loading, setLoading] = useState(true)
  const [form, setForm] = useState({ expense_date: new Date().toISOString().slice(0, 10), expense_category: 'MATERIAL', item_name: '', quantity: 1, unit: 'item', unit_price: '', buyer_role: 'OTHER', buyer_name: '', buyer_phone: '', notes: '' })
  const load = async () => { setLoading(true); try { const result = await api.get('/operational-expenses'); setRows(result.data?.data || []) } catch (error) { setMessage(error.response?.data?.message || 'Could not load expenses.') } finally { setLoading(false) } }
  useEffect(() => { load() }, [])
  const visible = useMemo(() => role === 'OWNER' && managerId ? rows.filter((row) => row.manager_user_id === managerId) : rows, [rows, role, managerId])
  const totals = useMemo(() => ({ total: visible.reduce((sum, row) => sum + Number(row.total_amount || 0), 0), paid: visible.filter((row) => row.payment_status === 'PAID').reduce((sum, row) => sum + Number(row.total_amount || 0), 0), awaiting: visible.filter((row) => row.approval_status === 'OWNER_APPROVED' && row.payment_status !== 'PAID').reduce((sum, row) => sum + Number(row.total_amount || 0), 0) }), [visible])
  const submit = async (event) => { event.preventDefault(); try { await api.post('/operational-expenses', form); setForm({ ...form, item_name: '', quantity: 1, unit_price: '', buyer_name: '', buyer_phone: '', notes: '' }); setMessage('Expense recorded and sent to your manager for approval.'); load() } catch (error) { setMessage(error.response?.data?.message || 'Could not record expense.') } }
  const act = async (id, action) => { const comments = action === 'request-changes' ? window.prompt('Reason for requested changes:') : ''; if (action === 'request-changes' && !comments) return; try { await api[action === 'pay' ? 'post' : 'put'](`/operational-expenses/${id}/${action}`, action === 'pay' ? undefined : { comments }); setMessage(action === 'pay' ? 'Expense paid to the MTN number recorded.' : 'Expense approval updated.'); load() } catch (error) { setMessage(error.response?.data?.message || 'Action failed.') } }
  return <div className="flex min-h-screen bg-slate-50"><AppSidebar /><main className="flex-1 p-4 md:p-8"><div className="mx-auto max-w-7xl space-y-6">
    <header className="flex flex-wrap items-end justify-between gap-4 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div><p className="text-xs font-semibold uppercase tracking-wider text-emerald-700">Controlled purchasing</p><h1 className="mt-2 text-3xl font-bold text-slate-900">Expenses and mining materials</h1><p className="mt-2 text-sm text-slate-500">Accountant records purchases; manager approves; owner gives final approval and sends payment to the recorded MTN number.</p></div>{role === 'OWNER' && <OwnerManagerSelector />}</header>
    {message && <div className="rounded-xl border border-amber-200 bg-amber-50 p-3 text-sm text-amber-900">{message}</div>}
    <section className="grid gap-4 sm:grid-cols-3"><Card label="Recorded value" value={money(totals.total)} tone="blue"/><Card label="Ready for owner payment" value={money(totals.awaiting)} tone="amber"/><Card label="Paid purchases" value={money(totals.paid)} tone="green"/></section>
    {role === 'ACCOUNTANT' && <form onSubmit={submit} className="grid gap-3 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm md:grid-cols-3"><input required type="date" value={form.expense_date} onChange={(e) => setForm({ ...form, expense_date: e.target.value })} className="rounded-lg border p-3"/><select value={form.expense_category} onChange={(e) => setForm({ ...form, expense_category: e.target.value })} className="rounded-lg border p-3"><option value="MATERIAL">Mining material</option><option value="EQUIPMENT">Equipment</option><option value="FUEL">Petroleum / fuel</option><option value="TOOL">Tool (spade, hoe, wheelbarrow)</option><option value="OTHER">Other expense</option></select><input required placeholder="Item or expense (e.g. petroleum)" value={form.item_name} onChange={(e) => setForm({ ...form, item_name: e.target.value })} className="rounded-lg border p-3"/><input required min="0.01" step="0.01" type="number" placeholder="Quantity" value={form.quantity} onChange={(e) => setForm({ ...form, quantity: e.target.value })} className="rounded-lg border p-3"/><input required placeholder="Unit (litre, piece, bag)" value={form.unit} onChange={(e) => setForm({ ...form, unit: e.target.value })} className="rounded-lg border p-3"/><input required min="0" step="0.01" type="number" placeholder="Unit price (RWF)" value={form.unit_price} onChange={(e) => setForm({ ...form, unit_price: e.target.value })} className="rounded-lg border p-3"/><select value={form.buyer_role} onChange={(e) => setForm({ ...form, buyer_role: e.target.value })} className="rounded-lg border p-3"><option value="OTHER">Supplier / other buyer</option><option value="ACCOUNTANT">Accountant bought it</option><option value="MANAGER">Manager bought it</option><option value="OWNER">Owner bought it</option></select><input required placeholder="Buyer / supplier full name" value={form.buyer_name} onChange={(e) => setForm({ ...form, buyer_name: e.target.value })} className="rounded-lg border p-3"/><input required placeholder="MTN number (078… or 079…)" value={form.buyer_phone} onChange={(e) => setForm({ ...form, buyer_phone: e.target.value })} className="rounded-lg border p-3"/><textarea placeholder="Reason or notes" value={form.notes} onChange={(e) => setForm({ ...form, notes: e.target.value })} className="min-h-24 rounded-lg border p-3 md:col-span-2"/><button className="rounded-lg bg-emerald-700 px-4 py-3 font-semibold text-white hover:bg-emerald-800">Record and send to manager</button></form>}
    <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between p-6"><div><h2 className="text-xl font-semibold">Purchasing register</h2><p className="mt-1 text-sm text-slate-500">Dates, buyer details, approvals, and payments remain visible for your management unit.</p></div><button onClick={load} className="rounded-lg border px-4 py-2 text-sm font-semibold">Refresh</button></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-50 text-left text-slate-600"><tr><th className="p-4">Date / item</th><th>Category</th><th>Quantity</th><th>Amount</th><th>Buyer / MTN number</th><th>Approval</th><th>Payment</th><th className="p-4">Action</th></tr></thead><tbody>{visible.map((row) => <tr className="border-t" key={row.expense_id}><td className="p-4"><strong>{row.item_name}</strong><br/><span className="text-slate-500">{row.expense_date}</span></td><td>{row.expense_category}</td><td>{row.quantity} {row.unit}</td><td className="font-semibold">{money(row.total_amount)}</td><td>{row.buyer_name}<br/><span className="text-slate-500">{row.buyer_phone}</span></td><td><span className={`rounded-full px-2 py-1 text-xs font-semibold ${badge(row.approval_status)}`}>{row.approval_status}</span></td><td><span className={`rounded-full px-2 py-1 text-xs font-semibold ${badge(row.payment_status)}`}>{row.payment_status}</span></td><td className="space-x-2 p-4 whitespace-nowrap">{role === 'MANAGER' && ['PENDING_MANAGER','CHANGES_REQUESTED'].includes(row.approval_status) && <><button onClick={() => act(row.expense_id, 'approve')} className="font-semibold text-emerald-700">Approve</button><button onClick={() => act(row.expense_id, 'request-changes')} className="font-semibold text-red-700">Changes</button></>}{role === 'OWNER' && row.approval_status === 'PENDING_OWNER' && <><button onClick={() => act(row.expense_id, 'approve')} className="font-semibold text-emerald-700">Final approve</button><button onClick={() => act(row.expense_id, 'request-changes')} className="font-semibold text-red-700">Changes</button></>}{role === 'OWNER' && row.approval_status === 'OWNER_APPROVED' && row.payment_status !== 'PAID' && <button onClick={() => act(row.expense_id, 'pay')} className="font-semibold text-blue-700">Pay MTN</button>}</td></tr>)}{!loading && !visible.length && <tr><td colSpan="8" className="p-6 text-slate-500">No expense or material purchase is recorded in this scope.</td></tr>}{loading && <tr><td colSpan="8" className="p-6 text-slate-500">Loading expenses…</td></tr>}</tbody></table></div></section>
  </div></main></div>
}
function Card({ label, value, tone }) { const colors = { blue: 'border-blue-200 bg-blue-50 text-blue-900', amber: 'border-amber-200 bg-amber-50 text-amber-900', green: 'border-emerald-200 bg-emerald-50 text-emerald-900' }; return <article className={`rounded-2xl border p-5 ${colors[tone]}`}><p className="text-xs font-semibold uppercase">{label}</p><p className="mt-2 text-2xl font-bold">{value}</p></article> }
