import { useEffect, useMemo, useState } from 'react'
import api from '../api/api'
import { useAuth } from '../context/authStore'
import { useLanguage } from '../context/LanguageContext'
import { useOwnerManagerScope } from '../context/OwnerManagerScope'
import OwnerManagerSelector from '../components/OwnerManagerSelector'
import AppSidebar from './Appsidebar'

const money = (value) => `${Number(value || 0).toLocaleString()} RWF`
const today = () => new Date().toISOString().slice(0, 10)
const initial = () => ({ expense_date: today(), expense_category: 'MATERIAL', item_name: '', quantity: 1, unit: 'item', unit_price: '', buyer_role: 'OTHER', buyer_name: '', buyer_phone: '', payment_method: 'SYSTEM_MOMO', external_payment_reference: '', external_paid_date: today(), notes: '' })

export default function OperationalExpensesPage() {
  const { user } = useAuth(); const { t } = useLanguage(); const role = user?.role_name; const { managerId } = useOwnerManagerScope()
  const [rows, setRows] = useState([]); const [form, setForm] = useState(initial); const [basket, setBasket] = useState([]); const [message, setMessage] = useState(''); const [loading, setLoading] = useState(false); const [dateRange, setDateRange] = useState({ from: '', to: '' })
  const load = async () => { setLoading(true); try { const response = await api.get('/operational-expenses'); setRows(response.data?.data || []) } catch (error) { setMessage(error.response?.data?.message || t('expenses.loadFailed')) } finally { setLoading(false) } }
  useEffect(() => { load() }, [])
  const visible = useMemo(() => rows.filter((row) => (role !== 'OWNER' || !managerId || row.manager_user_id === managerId) && (!dateRange.from || row.expense_date >= dateRange.from) && (!dateRange.to || row.expense_date <= dateRange.to)), [rows, role, managerId, dateRange])
  const total = visible.reduce((sum, row) => sum + Number(row.total_amount || 0), 0)
  const weekTotals = useMemo(() => Object.entries(visible.reduce((all, row) => { const date = new Date(`${row.expense_date}T00:00:00`); date.setDate(date.getDate() - ((date.getDay() + 6) % 7)); const week = date.toISOString().slice(0, 10); (all[week] ||= { count: 0, total: 0 }); all[week].count += 1; all[week].total += Number(row.total_amount || 0); return all }, {})).sort(([left], [right]) => right.localeCompare(left)), [visible])
  const line = () => ({ expense_category: form.expense_category, item_name: form.item_name.trim(), quantity: form.quantity, unit: form.unit.trim(), unit_price: form.unit_price, buyer_role: form.buyer_role, buyer_name: form.buyer_name.trim(), buyer_phone: form.buyer_phone.trim(), notes: form.notes.trim() })
  const valid = (item) => item.item_name && Number(item.quantity) > 0 && item.unit_price !== '' && Number(item.unit_price) >= 0 && item.buyer_name
  const addLine = () => { const item = line(); if (!valid(item)) return setMessage(t('expenses.lineRequired')); setBasket((current) => [...current, item]); setForm((current) => ({ ...current, item_name: '', quantity: 1, unit: 'item', unit_price: '', notes: '' })); setMessage(t('expenses.lineAdded')) }
  const submit = async (event) => { event.preventDefault(); const item = line(); const items = valid(item) ? [...basket, item] : basket; if (!items.length) return setMessage(t('expenses.basketRequired')); try { const response = await api.post('/operational-expenses', { ...form, items }); setMessage(t('expenses.recorded', { count: response.data?.data?.count || items.length })); setBasket([]); setForm(initial()); load() } catch (error) { setMessage(error.response?.data?.message || t('expenses.saveFailed')) } }
  const act = async (id, action) => { const comments = action === 'request-changes' ? window.prompt(t('expenses.changeReason')) : ''; if (action === 'request-changes' && !comments) return; try { await api[action === 'pay' ? 'post' : 'put'](`/operational-expenses/${id}/${action}`, action === 'pay' ? undefined : { comments }); setMessage(action === 'pay' ? t('expenses.paymentDone') : t('expenses.actionSaved')); load() } catch (error) { setMessage(error.response?.data?.message || t('expenses.actionFailed')) } }
  const bulk = async (action) => { const label = action === 'pay-all' ? t('expenses.bulkPay') : t('expenses.bulkApprove'); if (!window.confirm(t('expenses.bulkConfirm', { action: label }))) return; try { const response = await api.post(`/operational-expenses/${action}`, managerId ? { manager_user_id: managerId } : {}); const result = response.data?.data || {}; setMessage(action === 'pay-all' ? t('expenses.bulkPaid', { count: result.paid || 0, failed: result.failed?.length || 0 }) : t('expenses.bulkApproved', { count: result.approved || 0, failed: result.failed?.length || 0 })); load() } catch (error) { setMessage(error.response?.data?.message || t('expenses.bulkFailed')) } }
  const external = form.payment_method === 'EXTERNAL_RECORDED'
  return <div className="flex min-h-screen bg-slate-50"><AppSidebar/><main className="min-w-0 flex-1 p-4 md:p-8"><div className="mx-auto max-w-7xl space-y-6">
    <header className="rounded-2xl border border-blue-100 bg-white p-6 shadow-sm"><p className="text-xs font-bold uppercase tracking-wider text-blue-700">{t('expenses.eyebrow')}</p><h1 className="mt-2 text-3xl font-bold">{t('expenses.title')}</h1><p className="mt-2 text-sm text-slate-600">{t('expenses.description')}</p></header>
    {role === 'OWNER' && <OwnerManagerSelector/>}{message && <p className="rounded-xl bg-blue-50 p-4 text-sm text-blue-950">{message}</p>}
    {role === 'ACCOUNTANT' && <form onSubmit={submit} className="rounded-2xl border bg-white p-6 shadow-sm"><h2 className="text-xl font-bold">{t('expenses.recordBasket')}</h2><p className="mt-1 text-sm text-slate-600">{t('expenses.basketHelp')}</p><div className="mt-5 grid gap-3 md:grid-cols-3">
      <input required type="date" value={form.expense_date} onChange={(e)=>setForm({...form,expense_date:e.target.value})} className="rounded-lg border p-3"/><select value={form.expense_category} onChange={(e)=>setForm({...form,expense_category:e.target.value})} className="rounded-lg border p-3"><option value="MATERIAL">{t('expenses.material')}</option><option value="EQUIPMENT">{t('expenses.equipment')}</option><option value="FUEL">{t('expenses.fuel')}</option><option value="TOOL">{t('expenses.tool')}</option><option value="OTHER">{t('expenses.other')}</option></select><select value={form.payment_method} onChange={(e)=>setForm({...form,payment_method:e.target.value})} className="rounded-lg border p-3"><option value="SYSTEM_MOMO">{t('expenses.systemMomo')}</option><option value="EXTERNAL_RECORDED">{t('expenses.external')}</option></select>
      <input placeholder={t('expenses.item')} value={form.item_name} onChange={(e)=>setForm({...form,item_name:e.target.value})} className="rounded-lg border p-3"/><input type="number" min="0.01" step="0.01" placeholder={t('expenses.quantity')} value={form.quantity} onChange={(e)=>setForm({...form,quantity:e.target.value})} className="rounded-lg border p-3"/><input placeholder={t('expenses.unit')} value={form.unit} onChange={(e)=>setForm({...form,unit:e.target.value})} className="rounded-lg border p-3"/><input type="number" min="0" placeholder={t('expenses.unitPrice')} value={form.unit_price} onChange={(e)=>setForm({...form,unit_price:e.target.value})} className="rounded-lg border p-3"/><input placeholder={t('expenses.buyer')} value={form.buyer_name} onChange={(e)=>setForm({...form,buyer_name:e.target.value})} className="rounded-lg border p-3"/><input placeholder={external ? t('expenses.phoneOptional') : t('expenses.mtnNumber')} value={form.buyer_phone} onChange={(e)=>setForm({...form,buyer_phone:e.target.value})} className="rounded-lg border p-3"/>{external && <input required placeholder={t('expenses.receipt')} value={form.external_payment_reference} onChange={(e)=>setForm({...form,external_payment_reference:e.target.value})} className="rounded-lg border p-3"/>}<textarea placeholder={t('expenses.notes')} value={form.notes} onChange={(e)=>setForm({...form,notes:e.target.value})} className="min-h-24 rounded-lg border p-3 md:col-span-2"/>
    </div><div className="mt-4 flex flex-wrap gap-3"><button type="button" onClick={addLine} className="rounded-lg border border-blue-300 bg-blue-50 px-4 py-3 font-bold text-blue-800">{t('expenses.addLine')}</button><button className="rounded-lg bg-blue-600 px-4 py-3 font-bold text-white">{basket.length ? t('expenses.submitLines', { count: basket.length + 1 }) : t('expenses.submitExpense')}</button></div>{basket.length > 0 && <div className="mt-4 rounded-xl border border-blue-200 bg-blue-50 p-4"><p className="font-bold">{t('expenses.basket', { count: basket.length })}</p>{basket.map((item,index)=><div className="mt-2 flex justify-between text-sm" key={`${item.item_name}-${index}`}><span>{item.item_name} · {item.quantity} {item.unit}</span><strong>{money(Number(item.quantity) * Number(item.unit_price))}</strong></div>)}<button type="button" onClick={()=>setBasket([])} className="mt-3 text-sm font-bold text-red-700">{t('expenses.clearBasket')}</button></div>}</form>}
    <section className="overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3 p-6"><div><h2 className="text-xl font-bold">{t('expenses.register')}</h2><p className="text-sm text-slate-600">{t('expenses.selectedTotal')}: {money(total)}</p></div><div className="flex flex-wrap items-center gap-2"><label className="text-sm font-semibold">{t('expenses.from')}<input type="date" value={dateRange.from} onChange={(e)=>setDateRange({...dateRange,from:e.target.value})} className="ml-1 rounded border p-2"/></label><label className="text-sm font-semibold">{t('expenses.to')}<input type="date" value={dateRange.to} onChange={(e)=>setDateRange({...dateRange,to:e.target.value})} className="ml-1 rounded border p-2"/></label><button onClick={()=>setDateRange({from:'',to:''})} className="rounded-lg border px-3 py-2 font-bold text-slate-700">{t('expenses.allDates')}</button>{['MANAGER','OWNER'].includes(role) && <button onClick={()=>bulk('approve-all')} className="rounded-lg border border-emerald-200 px-4 py-2 font-bold text-emerald-700">{t('expenses.approveAll')}</button>}{role === 'OWNER' && <button onClick={()=>bulk('pay-all')} className="rounded-lg bg-blue-600 px-4 py-2 font-bold text-white">{t('expenses.payAll')}</button>}<button onClick={load} className="rounded-lg border px-4 py-2 font-bold text-blue-700">{t('common.refresh')}</button></div></div>
    <div className="grid gap-3 border-y bg-slate-50 p-4 md:grid-cols-3">{weekTotals.map(([week,summary])=><div key={week} className="rounded-lg border bg-white p-3"><p className="text-xs font-bold uppercase text-slate-600">{t('expenses.weekStarting', { date: week })}</p><p className="mt-1 font-bold text-slate-900">{money(summary.total)}</p><p className="text-xs text-slate-600">{t('expenses.records', { count: summary.count })}</p></div>)}{!weekTotals.length&&<p className="text-sm text-slate-600">{t('expenses.noWeekly')}</p>}</div>
    <div className="overflow-x-auto"><table className="min-w-[900px] w-full text-sm"><thead className="bg-slate-50 text-left"><tr><th className="p-4">{t('expenses.dateItem')}</th><th>{t('expenses.buyer')}</th><th>{t('common.amount')}</th><th>{t('expenses.approval')}</th><th>{t('expenses.payment')}</th><th className="p-4">{t('common.actions')}</th></tr></thead><tbody>{visible.map((row)=><tr className="border-t" key={row.expense_id}><td className="p-4"><b>{row.item_name}</b><br/><span className="text-slate-600">{row.expense_date} · {row.quantity} {row.unit} · {row.expense_category}</span></td><td>{row.buyer_name}<br/><span className="text-slate-600">{row.buyer_phone || row.external_payment_reference || t('expenses.external')}</span></td><td>{money(row.total_amount)}</td><td>{row.approval_status}</td><td>{row.payment_method === 'EXTERNAL_RECORDED' ? t('expenses.externalPaid') : row.payment_status}</td><td className="p-4 whitespace-nowrap">{role === 'MANAGER' && ['PENDING_MANAGER','CHANGES_REQUESTED'].includes(row.approval_status) && <><button onClick={()=>act(row.expense_id,'approve')} className="mr-2 font-bold text-emerald-700">{t('expenses.approve')}</button><button onClick={()=>act(row.expense_id,'request-changes')} className="font-bold text-red-700">{t('status.changesRequested')}</button></>}{role === 'OWNER' && row.approval_status === 'PENDING_OWNER' && <button onClick={()=>act(row.expense_id,'approve')} className="font-bold text-emerald-700">{t('expenses.finalApprove')}</button>}{role === 'OWNER' && row.payment_method !== 'EXTERNAL_RECORDED' && row.approval_status === 'OWNER_APPROVED' && row.payment_status !== 'PAID' && <button onClick={()=>act(row.expense_id,'pay')} className="ml-2 font-bold text-blue-700">{t('expenses.payMtn')}</button>}</td></tr>)}{!loading && !visible.length && <tr><td colSpan="6" className="p-8 text-center text-slate-500">{t('expenses.noRecords')}</td></tr>}</tbody><tfoot className="bg-blue-50 font-bold text-slate-900"><tr><td className="p-4" colSpan="2">{t('common.total')}</td><td>{money(total)}</td><td colSpan="3"></td></tr></tfoot></table></div></section>
  </div></main></div>
}
