import { useState } from 'react'
import api from '../api/api'
import AppSidebar from './Appsidebar'
const money = (v) => `${Number(v || 0).toLocaleString()} RWF`
const dateTime = (value) => value ? new Date(value).toLocaleString() : '-'
export default function PaymentProofPage() {
  const [search, setSearch] = useState(''); const [start, setStart] = useState(''); const [end, setEnd] = useState(''); const [rows, setRows] = useState([]); const [loading,setLoading]=useState(false); const [message,setMessage]=useState('Search a worker name or employee code to verify payment evidence.')
  const load=async(e)=>{e?.preventDefault();setLoading(true);try{const r=await api.get('/payments/worker-proof',{params:{search,start_date:start,end_date:end}});setRows(r.data?.data||[]);setMessage(`${r.data?.data?.length||0} payment record(s) found.`)}catch(err){setMessage(err.response?.data?.message||'Could not search payment proof.')}finally{setLoading(false)}}
  return <div className="flex min-h-screen bg-slate-50"><AppSidebar/><main className="flex-1 p-4 md:p-8"><div className="mx-auto max-w-7xl space-y-6"><header className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><p className="text-xs font-semibold uppercase tracking-wider text-emerald-700">Owner fraud-control center</p><h1 className="mt-2 text-3xl font-bold">Worker payment proof</h1><p className="mt-2 text-sm text-slate-600">Search by worker name or employee code before making any replacement payment. A PAID record includes the transaction reference and time; failed records show the exact reason.</p></header><form onSubmit={load} className="grid gap-3 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm md:grid-cols-4"><input required value={search} onChange={e=>setSearch(e.target.value)} placeholder="Worker name or code" className="rounded-lg border p-3"/><input type="date" value={start} onChange={e=>setStart(e.target.value)} className="rounded-lg border p-3"/><input type="date" value={end} onChange={e=>setEnd(e.target.value)} className="rounded-lg border p-3"/><button className="rounded-lg bg-emerald-700 px-4 py-3 font-semibold text-white">{loading?'Searching…':'Find payment proof'}</button></form><p className="rounded-lg border border-blue-200 bg-blue-50 p-3 text-sm text-blue-900">{message}</p><section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-100 text-left text-slate-700"><tr><th className="p-4">Worker</th><th>Amount</th><th>Phone</th><th>Status</th><th>Payment proof</th><th>Failure reason</th></tr></thead><tbody>{rows.map(row=><tr key={row.payment_id} className="border-t"><td className="p-4"><strong>{row.employees?.first_name} {row.employees?.last_name}</strong><br/><span className="text-slate-500">{row.employees?.employee_code}</span></td><td className="font-semibold">{money(row.amount)}</td><td>{row.receiver_phone||row.phone||'-'}</td><td><span className={`rounded-full px-2 py-1 text-xs font-bold ${row.payment_status==='PAID'?'bg-emerald-100 text-emerald-800':'bg-red-100 text-red-800'}`}>{row.payment_status}</span></td><td>{row.payment_status==='PAID'?<><strong>Paid successfully</strong><br/><span className="text-slate-500">Ref: {row.reference_id||row.transaction_reference||'-'}<br/>{dateTime(row.paid_at||row.payment_date||row.created_at)}</span></>:'No successful transfer'}</td><td className="text-red-700">{row.failure_reason||'-'}</td></tr>)}{!rows.length&&<tr><td className="p-6 text-slate-500" colSpan="6">No payment proof loaded yet.</td></tr>}</tbody></table></div></section></div></main></div>
}
