import { useEffect, useMemo, useState } from 'react';
import toast from 'react-hot-toast';
import api from '../api/api';
import { useAuth } from '../context/authStore';
import AppSidebar from './Appsidebar';

const today = new Date().toISOString().slice(0, 10);
const unwrap = (response) => response?.data?.data ?? response?.data ?? response;
const weekKey = (dateValue) => { const date = new Date(`${dateValue}T00:00:00`); const monday = new Date(date); monday.setDate(date.getDate() - ((date.getDay() + 6) % 7)); return monday.toISOString().slice(0, 10); };

export default function ProductionPage() {
  const { user } = useAuth(); const [records, setRecords] = useState([]); const [workers, setWorkers] = useState([]); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false);
  const [range, setRange] = useState({ from: '', to: '' }); const [form, setForm] = useState({ employee_id: '', production_date: today, mineral_type: '', quantity: '', unit: 'kg', activity_details: '', working_hours: '', remarks: '', workers: [] });
  const load = async () => { setLoading(true); try { const [production, employeeList] = await Promise.all([api.get('/production'), api.get('/employees')]); setRecords(Array.isArray(unwrap(production)) ? unwrap(production) : []); setWorkers(Array.isArray(unwrap(employeeList)) ? unwrap(employeeList) : []); } catch (error) { toast.error(error.response?.data?.message || 'Could not load production operations.'); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const canRecord = ['ACCOUNTANT', 'SUPER_ADMIN'].includes(user?.role_name);
  const set = (key, value) => setForm((current) => ({ ...current, [key]: value }));
  const toggleWorker = (employee_id) => setForm((current) => ({ ...current, workers: current.workers.some((worker) => worker.employee_id === employee_id) ? current.workers.filter((worker) => worker.employee_id !== employee_id) : [...current.workers, { employee_id, working_hours: '' }] }));
  const save = async (event) => { event.preventDefault(); setSaving(true); try { await api.post('/production', { ...form, quantity: Number(form.quantity), working_hours: form.working_hours === '' ? null : Number(form.working_hours), workers: form.workers.map((worker) => ({ ...worker, working_hours: worker.working_hours === '' ? null : Number(worker.working_hours) })) }); toast.success('Production operation recorded.'); setForm({ employee_id: '', production_date: today, mineral_type: '', quantity: '', unit: 'kg', activity_details: '', working_hours: '', remarks: '', workers: [] }); load(); } catch (error) { toast.error(error.response?.data?.message || 'Could not record production.'); } finally { setSaving(false); } };
  const filtered = useMemo(() => records.filter((record) => (!range.from || record.production_date >= range.from) && (!range.to || record.production_date <= range.to)), [records, range]);
  const groups = useMemo(() => Object.entries(filtered.reduce((all, record) => { const key = weekKey(record.production_date); (all[key] ||= []).push(record); return all; }, {})).sort(([left], [right]) => right.localeCompare(left)), [filtered]);
  const total = filtered.reduce((sum, record) => sum + Number(record.quantity || 0), 0);
  return <div className="flex min-h-screen bg-slate-50">{user && <AppSidebar />}<main className="min-w-0 flex-1 p-5 md:p-8"><div className="mx-auto max-w-7xl space-y-6"><header className="rounded-2xl border border-blue-100 bg-white p-6 shadow-sm"><p className="text-xs font-bold uppercase tracking-wider text-blue-700">Daily operations</p><h1 className="mt-2 text-3xl font-bold text-slate-900">Production and mineral operations</h1><p className="mt-2 text-sm text-slate-600">Records are grouped by Monday–Sunday week so every extraction period has its own clear total.</p></header>
    {canRecord && <form onSubmit={save} className="rounded-2xl border bg-white p-5 shadow-sm"><h2 className="font-bold text-slate-900">Record production</h2><div className="mt-4 grid gap-3 md:grid-cols-3">{[['production_date','Date','date'],['mineral_type','Mineral type','text'],['quantity','Quantity extracted','number'],['unit','Unit','text'],['working_hours','Operation hours','number']].map(([key,label,type]) => <label key={key} className="text-sm font-semibold text-slate-700"><span className="mb-1 block">{label}</span><input required={['production_date','mineral_type','quantity','unit'].includes(key)} type={type} min={type === 'number' ? '0' : undefined} value={form[key]} onChange={(event) => set(key, event.target.value)} className="w-full rounded border border-slate-200 p-2" /></label>)}<label className="text-sm font-semibold text-slate-700"><span className="mb-1 block">Lead worker</span><select required value={form.employee_id} onChange={(event) => set('employee_id', event.target.value)} className="w-full rounded border border-slate-200 p-2"><option value="">Select worker</option>{workers.map((worker) => <option key={worker.employee_id} value={worker.employee_id}>{worker.employee_code} {worker.first_name} {worker.last_name}</option>)}</select></label><label className="text-sm font-semibold text-slate-700 md:col-span-2"><span className="mb-1 block">Activity details</span><input value={form.activity_details} onChange={(event) => set('activity_details', event.target.value)} className="w-full rounded border border-slate-200 p-2" /></label></div><div className="mt-4"><p className="text-sm font-bold text-slate-700">Workers involved</p><div className="mt-2 grid gap-2 md:grid-cols-2">{workers.map((worker) => { const involved = form.workers.some((item) => item.employee_id === worker.employee_id); return <label key={worker.employee_id} className="flex items-center gap-2 rounded border p-2 text-sm"><input type="checkbox" checked={involved} onChange={() => toggleWorker(worker.employee_id)} /><span>{worker.first_name} {worker.last_name}</span></label>; })}</div></div><button disabled={saving} className="mt-4 rounded-lg bg-blue-600 px-4 py-2 font-bold text-white disabled:opacity-60">{saving ? 'Saving…' : 'Save production'}</button></form>}
    <section className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-bold uppercase text-blue-700">Production review</p><h2 className="mt-1 text-xl font-bold">Filter date range and weekly totals</h2></div><div className="flex flex-wrap gap-2"><label className="text-sm font-semibold">From<input type="date" value={range.from} onChange={(event) => setRange({ ...range, from: event.target.value })} className="ml-2 rounded border p-2" /></label><label className="text-sm font-semibold">To<input type="date" value={range.to} onChange={(event) => setRange({ ...range, to: event.target.value })} className="ml-2 rounded border p-2" /></label><button onClick={() => setRange({ from: '', to: '' })} className="rounded-lg border px-3 py-2 font-bold text-slate-700">All dates</button></div></div><div className="mt-4 rounded-xl bg-blue-50 p-4"><p className="text-xs font-bold uppercase text-blue-700">Selected-range total</p><p className="mt-1 text-2xl font-bold text-slate-900">{Number(total).toLocaleString()} total units</p><p className="text-sm text-slate-600">{filtered.length} production record(s)</p></div></section>
    {loading ? <p className="text-slate-600">Loading…</p> : groups.map(([week, rows]) => { const weekTotal = rows.reduce((sum, row) => sum + Number(row.quantity || 0), 0); return <section key={week} className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex justify-between gap-4 border-b bg-slate-50 p-4"><div><p className="text-xs font-bold uppercase text-blue-700">Week starting {week}</p><h2 className="mt-1 font-bold text-slate-900">{rows.length} extraction record(s)</h2></div><p className="text-xl font-bold text-slate-900">{Number(weekTotal).toLocaleString()} units</p></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="text-left text-slate-600"><tr><th className="p-3">Date</th><th>Mineral</th><th>Quantity</th><th>Lead worker</th><th>Hours</th></tr></thead><tbody>{rows.map((row) => <tr className="border-t" key={row.production_id}><td className="p-3">{row.production_date}</td><td>{row.mineral_type}</td><td className="font-bold">{row.quantity} {row.unit}</td><td>{row.employees?.first_name} {row.employees?.last_name}</td><td>{row.working_hours || '—'}</td></tr>)}</tbody><tfoot className="bg-blue-50 font-bold text-slate-900"><tr><td colSpan="2" className="p-3">Week total</td><td className="p-3">{Number(weekTotal).toLocaleString()} units</td><td colSpan="2" /></tr></tfoot></table></div></section>; })}{!loading && !groups.length && <section className="rounded-2xl border bg-white p-8 text-center text-slate-500">No production records match this date range.</section>}
  </div></main></div>;
}
