import { useEffect, useMemo, useState } from 'react'
import api from '../api/api'
import { useAuth } from '../context/authStore'
import AppSidebar from './Appsidebar'
import OwnerManagerSelector from '../components/OwnerManagerSelector'
import { useOwnerManagerScope } from '../context/OwnerManagerScope'
const money = (v) => `${Number(v || 0).toLocaleString()} RWF`
export default function WorkerConsumptionsPage() {
  const { user } = useAuth(); const role = user?.role_name; const { managerId } = useOwnerManagerScope()
  const [employees, setEmployees] = useState([]); const [shops, setShops] = useState([]); const [rows, setRows] = useState([]); const [message, setMessage] = useState('')
  const [form, setForm] = useState({ employee_id: '', shopkeeper_id: '', consumption_date: new Date().toISOString().slice(0, 10), item_name: '', quantity: 1, unit_price: '', remarks: '' }); const [shopForm, setShopForm] = useState({ shopkeeper_name: '', phone: '' })
  const load = async () => { try { const [employeeResult, consumptionResult, shopResult] = await Promise.all([api.get('/employees'), api.get('/worker-consumptions'), api.get('/shopkeepers')]); setEmployees(employeeResult.data?.data || []); setRows(consumptionResult.data?.data || []); setShops(shopResult.data?.data || []) } catch (error) { setMessage(error.response?.data?.message || 'Could not load worker-item workflow.') } }
  useEffect(() => { load() }, [])
  const visibleRows = useMemo(() => role === 'OWNER' && managerId ? rows.filter((row) => row.manager_user_id === managerId) : rows, [rows, managerId, role])
  const submitShop = async (event) => { event.preventDefault(); try { await api.post('/shopkeepers', shopForm); setShopForm({ shopkeeper_name: '', phone: '' }); setMessage('Shopkeeper created for your management unit.'); load() } catch (error) { setMessage(error.response?.data?.message || 'Could not create shopkeeper.') } }
  const submit = async (event) => { event.preventDefault(); try { await api.post('/worker-consumptions', form); setForm({ ...form, employee_id: '', shopkeeper_id: '', item_name: '', quantity: 1, unit_price: '', remarks: '' }); setMessage('Worker item sent to the manager for approval.'); load() } catch (error) { setMessage(error.response?.data?.message || 'Could not record item.') } }
  const act = async (id, action) => { const comments = action === 'request-changes' ? window.prompt('Reason for changes:') : ''; if (action === 'request-changes' && !comments) return; try { await api[action === 'pay' ? 'post' : 'put'](`/worker-consumptions/${id}/${action}`, action === 'pay' ? undefined : { comments }); setMessage(action === 'pay' ? 'Shopkeeper paid successfully.' : 'Approval status updated.'); load() } catch (error) { setMessage(error.response?.data?.message || 'Action failed.') } }
  return <div className="flex min-h-screen bg-slate-50"><AppSidebar /><main className="flex-1 p-6 lg:p-10"><div className="mx-auto max-w-7xl space-y-6"><header className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-3xl font-bold">Worker items and shopkeeper payments</h1><p className="text-slate-600">Accountant records purchases; manager approves, owner approves and pays the shopkeeper.</p></div>{role === 'OWNER' && <OwnerManagerSelector />}</header>{message && <div className="rounded-xl border border-amber-200 bg-amber-50 p-3">{message}</div>}
  {role === 'MANAGER' && <form onSubmit={submitShop} className="grid gap-3 rounded-2xl bg-white p-6 shadow-sm md:grid-cols-3"><input required placeholder="Shopkeeper name" value={shopForm.shopkeeper_name} onChange={(e) => setShopForm({ ...shopForm, shopkeeper_name: e.target.value })} className="rounded-lg border p-3"/><input required placeholder="Valid MTN phone e.g. 078..." value={shopForm.phone} onChange={(e) => setShopForm({ ...shopForm, phone: e.target.value })} className="rounded-lg border p-3"/><button className="rounded-lg bg-blue-600 px-4 py-3 font-semibold text-white">Add shopkeeper</button></form>}
  {role === 'ACCOUNTANT' && <form onSubmit={submit} className="grid gap-3 rounded-2xl bg-white p-6 shadow-sm md:grid-cols-3"><select required value={form.employee_id} onChange={(e) => setForm({ ...form, employee_id: e.target.value })} className="rounded-lg border p-3"><option value="">Select worker</option>{employees.map((employee) => <option key={employee.employee_id} value={employee.employee_id}>{employee.employee_code} — {employee.first_name} {employee.last_name}</option>)}</select><select required value={form.shopkeeper_id} onChange={(e) => setForm({ ...form, shopkeeper_id: e.target.value })} className="rounded-lg border p-3"><option value="">Select shopkeeper</option>{shops.map((shop) => <option key={shop.shopkeeper_id} value={shop.shopkeeper_id}>{shop.shopkeeper_name} — {shop.phone}</option>)}</select><input required type="date" value={form.consumption_date} onChange={(e) => setForm({ ...form, consumption_date: e.target.value })} className="rounded-lg border p-3"/><input required placeholder="Item" value={form.item_name} onChange={(e) => setForm({ ...form, item_name: e.target.value })} className="rounded-lg border p-3"/><input required type="number" min="0.01" step="0.01" value={form.quantity} onChange={(e) => setForm({ ...form, quantity: e.target.value })} className="rounded-lg border p-3"/><input required type="number" min="0" placeholder="Unit price" value={form.unit_price} onChange={(e) => setForm({ ...form, unit_price: e.target.value })} className="rounded-lg border p-3"/><button className="rounded-lg bg-amber-500 px-4 py-3 font-semibold">Record and send for approval</button></form>}
  <section className="overflow-hidden rounded-2xl bg-white shadow-sm"><div className="p-6"><h2 className="text-xl font-semibold">Purchases, approvals, and shopkeeper payment</h2></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-50 text-left"><tr><th className="p-4">Worker / Shopkeeper</th><th>Date</th><th>Item</th><th>Amount</th><th>Approval</th><th>Payment</th><th>Action</th></tr></thead><tbody>{visibleRows.map((row) => <tr className="border-t" key={row.consumption_id}><td className="p-4"><strong>{row.employees?.first_name} {row.employees?.last_name}</strong><br/><span className="text-slate-500">{row.shopkeepers?.shopkeeper_name || 'Legacy item'}</span></td><td>{row.consumption_date}</td><td>{row.item_name} × {row.quantity}</td><td className="font-semibold">{money(row.total_amount)}</td><td>{row.approval_status || 'LEGACY'}</td><td>{row.shopkeeper_payment_status || 'UNPAID'}</td><td className="space-x-2">{role === 'MANAGER' && row.approval_status === 'PENDING_MANAGER' && <><button onClick={() => act(row.consumption_id, 'approve')} className="text-emerald-700">Approve</button><button onClick={() => act(row.consumption_id, 'request-changes')} className="text-red-700">Changes</button></>}{role === 'OWNER' && row.approval_status === 'PENDING_OWNER' && <button onClick={() => act(row.consumption_id, 'approve')} className="text-emerald-700">Final approve</button>}{role === 'OWNER' && row.approval_status === 'OWNER_APPROVED' && <button onClick={() => act(row.consumption_id, 'pay')} className="font-semibold text-blue-700">Pay shopkeeper</button>}</td></tr>)}{!visibleRows.length && <tr><td colSpan="7" className="p-6 text-slate-500">No worker purchases in this manager scope.</td></tr>}</tbody></table></div></section></div></main></div>
}
