import { useState } from 'react'
import { BadgeDollarSign, CreditCard, Package, Pickaxe, ReceiptText, Users, Wallet, Landmark } from 'lucide-react'
import { useLanguage } from '../context/LanguageContext'

const money = (value) => `${Number(value || 0).toLocaleString()} RWF`
const rangeLabel = (period, language) => {
  const current = new Date(); const iso = (date) => date.toLocaleDateString(language === 'rw' ? 'rw-RW' : language === 'fr' ? 'fr-FR' : 'en-GB', { day: '2-digit', month: 'short', year: 'numeric' })
  if (period === 'today') return iso(current)
  if (period === 'week') { const start = new Date(current); start.setDate(start.getDate() - (start.getDay() || 7) + 1); const end = new Date(start); end.setDate(end.getDate() + 6); return `${iso(start)} – ${iso(end)}` }
  if (period === 'two_weeks' || period === 'three_weeks') { const start = new Date(current); start.setDate(start.getDate() - (period === 'two_weeks' ? 13 : 20)); return `${iso(start)} – ${iso(current)}` }
  if (period === 'month') return current.toLocaleDateString(language === 'rw' ? 'rw-RW' : language === 'fr' ? 'fr-FR' : 'en-GB', { month: 'long', year: 'numeric' })
  return String(current.getFullYear())
}
function Metric({ icon: Icon, label, value, tone = 'blue', note }) { const tones = { blue: 'border-blue-200 bg-blue-50 text-blue-800', green: 'border-emerald-200 bg-emerald-50 text-emerald-800', amber: 'border-amber-200 bg-amber-50 text-amber-900', red: 'border-red-200 bg-red-50 text-red-800' }; return <article className={`rounded-xl border p-4 shadow-sm ${tones[tone]}`}><div className="flex items-start justify-between gap-3"><p className="text-xs font-bold uppercase tracking-wide">{label}</p><Icon size={18} /></div><p className="mt-3 text-2xl font-bold text-slate-900">{value}</p>{note && <p className="mt-2 text-xs text-slate-600">{note}</p>}</article> }

export default function PeriodOperationsCards({ periods = {}, title }) {
  const { t, language } = useLanguage(); const [period, setPeriod] = useState('week'); const data = periods[period] || {}
  const periodLabels = { today: t('periodCards.today'), week: t('periodCards.week'), two_weeks: t('periodCards.twoWeeks'), three_weeks: t('periodCards.threeWeeks'), month: t('periodCards.month'), year: t('periodCards.year') }
  const metrics = [
    [Wallet,'periodCards.fixedGross',money(data.fixed_payroll_gross),'blue','periodCards.fixedGrossHelp'], [Wallet,'periodCards.fixedNet',money(data.fixed_payroll_net),'green','periodCards.fixedNetHelp'], [BadgeDollarSign,'periodCards.advanceDeductions',`−${money(data.fixed_payroll_advances)}`,'amber','periodCards.advanceDeductionsHelp'], [ReceiptText,'periodCards.consumptionDeductions',`−${money(data.fixed_payroll_consumptions)}`,'red','periodCards.consumptionDeductionsHelp'], [Users,'periodCards.flexibleWork',money(data.flexible_work_value),'blue',null,{ count: Number(data.flexible_work_days || 0) }], [Wallet,'periodCards.flexiblePayroll',money(data.flexible_payroll_total),'green','periodCards.flexiblePayrollHelp'], [BadgeDollarSign,'periodCards.advanceRequests',money(data.advances_total),'amber','periodCards.advanceRequestsHelp'], [CreditCard,'periodCards.readyToPay',money(data.ready_to_pay),'green','periodCards.readyToPayHelp'], [Users,'periodCards.directWorkers',money(data.owner_direct_workers_total),'blue',null,{ amount: money(data.owner_direct_workers_due) }], [Package,'navigation.foodSupplies',money(data.food_total),'amber','periodCards.foodRecorded'], [ReceiptText,'navigation.expenses',money(data.expenses_total),'red','periodCards.expensesHelp'], [Package,'periodCards.consumptions',money(data.consumptions_total),'amber','periodCards.consumptionsHelp'], [Pickaxe,'periodCards.minerals',`${Number(data.production_quantity || 0).toLocaleString()} kg`,'blue',null,{ count: Number(data.pending_approvals || 0) }]
  ]
  return <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><div><p className="text-xs font-bold uppercase tracking-wider text-blue-700">{t('periodCards.realTotals', { range: rangeLabel(period, language) })}</p><h2 className="mt-1 text-xl font-bold text-slate-900">{title || t('periodCards.defaultTitle')}</h2><p className="mt-1 text-sm text-slate-600">{t('periodCards.payrollExplanation')}</p></div><div className="flex flex-wrap gap-2">{Object.keys(periodLabels).map((key) => <button key={key} onClick={() => setPeriod(key)} className={`rounded-lg px-3 py-2 text-sm font-semibold ${period === key ? 'bg-blue-600 text-white' : 'border border-blue-200 text-blue-700 hover:bg-blue-50'}`}>{periodLabels[key]}</button>)}</div></div>
    <div className="mt-4 grid gap-3 md:grid-cols-3"><Info tone="blue" title={t('periodCards.grossEarned')} text={t('periodCards.grossEarnedHelp')} /><Info tone="green" title={t('periodCards.netSettlement')} text={t('periodCards.netSettlementHelp')} /><Info tone="amber" title={t('periodCards.noForecast')} text={t('periodCards.noForecastHelp')} /></div>
    <div className="mt-5 rounded-2xl border-2 border-blue-200 bg-gradient-to-r from-blue-50 via-white to-emerald-50 p-5 shadow-sm"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><div className="flex items-center gap-2 text-blue-800"><Landmark size={20}/><p className="text-xs font-bold uppercase tracking-wider">{t('periodCards.totalCommitment')}</p></div><p className="mt-2 text-3xl font-extrabold text-slate-950">{money(data.owner_gross_commitment)}</p><p className="mt-2 max-w-3xl text-sm text-slate-700">{data.owner_gross_formula || t('periodCards.formula')}</p></div><div className="rounded-xl border border-blue-100 bg-white/90 p-4 text-sm text-slate-700"><p className="font-bold text-slate-900">{t('periodCards.formulaTitle')}</p><p className="mt-2">{t('periodCards.formula')}</p><p className="mt-2 font-semibold text-amber-800">{t('periodCards.excluded')}</p></div></div><div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Mini title={t('periodCards.fixedWorkers')} value={money(data.fixed_workers_attendance_gross)} note={t('periodCards.fixedWorkersHelp')} tone="blue"/><Mini title={t('periodCards.flexibleWorkers')} value={money(data.flexible_work_value)} note={t('periodCards.flexibleWorkersHelp')} tone="violet"/><Mini title={t('periodCards.directWorkers')} value={money(data.owner_direct_workers_total)} note={t('periodCards.directWorkersHelp')} tone="cyan"/><Mini title={t('navigation.foodSupplies')} value={money(data.food_total)} note={t('periodCards.foodSuppliesHelp')} tone="amber"/><Mini title={t('navigation.expenses')} value={money(data.expenses_total)} note={t('periodCards.expensesHelp')} tone="red"/></div></div>
    <div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{metrics.map(([Icon,label,value,tone,note,values]) => <Metric key={label} icon={Icon} label={t(label)} value={value} tone={tone} note={note ? t(note, values) : label === 'periodCards.flexibleWork' ? t('periodCards.flexibleWorkHelp', values) : label === 'periodCards.directWorkers' ? t('periodCards.directWorkersDue', values) : label === 'periodCards.minerals' ? t('periodCards.mineralsHelp', values) : undefined}/>)}</div>
  </section>
}
function Info({ tone, title, text }) { const colors = { blue:'border-blue-200 bg-blue-50 text-blue-800', green:'border-emerald-200 bg-emerald-50 text-emerald-800', amber:'border-amber-200 bg-amber-50 text-amber-900' }; return <div className={`rounded-xl border p-4 ${colors[tone]}`}><p className="text-xs font-bold uppercase">{title}</p><p className="mt-2 text-sm text-slate-700">{text}</p></div> }
function Mini({ title, value, note, tone }) { const colors = { blue:'text-blue-700', violet:'text-violet-700', cyan:'text-cyan-700', amber:'text-amber-700', red:'text-red-700' }; return <div className="rounded-lg bg-white p-3"><p className={`text-xs font-bold uppercase ${colors[tone]}`}>{title}</p><p className="mt-1 font-bold text-slate-950">{value}</p><p className="mt-1 text-xs text-slate-500">{note}</p></div> }
