const supabase = require("../config/supabase");

const repaymentCap = () => {
    const configured = Number(process.env.ADVANCE_DEDUCTION_PER_PAYROLL);
    return Number.isFinite(configured) && configured > 0 ? configured : Number.MAX_SAFE_INTEGER;
};

const getAdvanceBalance = async (advance) => {
    const { data, error } = await supabase.from("salary_advance_deductions").select("amount").eq("advance_id", advance.advance_id);
    if (error) throw error;
    const deducted = (data || []).reduce((sum, item) => sum + Number(item.amount || 0), 0);
    return { deducted, remaining: Math.max(0, Number(advance.amount || 0) - deducted) };
};

const listOutstandingPaidAdvances = async (employeeId) => {
    const { data, error } = await supabase.from("salary_advances")
        .select("advance_id, employee_id, amount, status, payment_status")
        .eq("employee_id", employeeId)
        .eq("status", "OWNER_APPROVED")
        .eq("payment_status", "PAID")
        .order("request_date", { ascending: true });
    if (error) throw error;
    const balances = await Promise.all((data || []).map(async advance => ({ ...advance, ...(await getAdvanceBalance(advance)) })));
    return balances.filter(advance => advance.remaining > 0);
};

const applyPayrollAdvanceDeductions = async ({ payrollId, employeeId, createdBy }) => {
    const existing = await supabase.from("salary_advance_deductions").select("amount").eq("payroll_id", payrollId);
    if (existing.error) throw existing.error;
    if (existing.data?.length) return existing.data.reduce((sum, item) => sum + Number(item.amount || 0), 0);

    let available = repaymentCap();
    let total = 0;
    for (const advance of await listOutstandingPaidAdvances(employeeId)) {
        if (available <= 0) break;
        const amount = Math.min(advance.remaining, available);
        const { error } = await supabase.from("salary_advance_deductions").insert([{
            advance_id: advance.advance_id, payroll_id: payrollId, amount, created_by: createdBy || null
        }]);
        // A duplicate generated by a retry is harmless: use the unique ledger row.
        if (error && error.code !== "23505") throw error;
        const balance = await getAdvanceBalance(advance);
        const settled = balance.remaining === 0;
        const { error: updateError } = await supabase.from("salary_advances").update({
            amount_deducted: balance.deducted,
            remaining_balance: balance.remaining,
            deducted_by_payroll_id: payrollId,
            deduction_status: settled ? "SETTLED" : "PARTIALLY_DEDUCTED"
        }).eq("advance_id", advance.advance_id);
        if (updateError) throw updateError;
        total += amount;
        available -= amount;
    }
    return total;
};

module.exports = { applyPayrollAdvanceDeductions, listOutstandingPaidAdvances, getAdvanceBalance };
