const { randomUUID } = require('crypto');
const supabase = require('../config/supabase');
const { requireCompanyIds, resolveAuthorizedCompanyId } = require('../utils/companyScope');
const { normalizeMtnRwandaPhone } = require('../utils/rwandaPhone');
const { getPaymentProvider } = require('./paymentProviders');

const assertOwner = (user) => { if (user?.role_name !== 'OWNER') throw new Error('Only the Owner can access monthly staff records.'); };
const today = () => new Date().toISOString().slice(0, 10);
const monthPeriod = (month, year) => { const m = Number(month); const y = Number(year); if (!Number.isInteger(m) || m < 1 || m > 12 || !Number.isInteger(y) || y < 2000) throw new Error('Choose a valid payroll month and year.'); return { month: m, year: y }; };
const list = async (user) => { assertOwner(user); const { data, error } = await supabase.from('monthly_staff').select('*, monthly_staff_advances(*), monthly_staff_payroll(*)').in('company_id', requireCompanyIds(user)).eq('owner_user_id', user.user_id).order('created_at', { ascending: false }); if (error) throw error; return data || []; };
const get = async (id, user) => { const row = (await list(user)).find((item) => item.monthly_staff_id === id); if (!row) throw new Error('Monthly staff record was not found in your Owner scope.'); return row; };
const create = async (payload, user) => {
  assertOwner(user); const company_id = resolveAuthorizedCompanyId(user, payload.company_id); const staff_type = String(payload.staff_type || '').toUpperCase(); const full_name = String(payload.full_name || '').trim(); const monthly_salary = Number(payload.monthly_salary || 0); const is_private = staff_type === 'OWNER_PRIVATE';
  if (!['ACCOUNTANT','SECURITY','OWNER_PRIVATE'].includes(staff_type)) throw new Error('Choose Accountant, Security, or Owner private staff.');
  if (!full_name || !Number.isFinite(monthly_salary) || monthly_salary <= 0 || !payload.start_date) throw new Error('Name, start date, and a positive monthly salary are required.');
  const { data, error } = await supabase.from('monthly_staff').insert([{ company_id, owner_user_id: user.user_id, linked_employee_id: payload.linked_employee_id || null, staff_type, full_name, national_id: String(payload.national_id || '').trim() || null, momo_phone: normalizeMtnRwandaPhone(payload.momo_phone), monthly_salary, start_date: payload.start_date, is_private }]).select().single(); if (error) throw error; return data;
};
const eligibleForAdvance = (staff) => Math.floor((new Date(`${today()}T00:00:00Z`) - new Date(`${staff.start_date}T00:00:00Z`)) / 86400000) + 1 >= 15;
const requestAdvance = async (id, payload, user) => { const staff = await get(id, user); if (!['ACCOUNTANT','SECURITY'].includes(staff.staff_type)) throw new Error('Owner-private staff do not use the monthly-staff advance feature.'); if (!eligibleForAdvance(staff)) throw new Error('A monthly-staff advance becomes available after 15 calendar days of work.'); const amount = Number(payload.amount || 0); if (!Number.isFinite(amount) || amount <= 0 || amount > Number(staff.monthly_salary) / 2) throw new Error('Advance must be positive and cannot exceed half of the monthly salary.'); const { data, error } = await supabase.from('monthly_staff_advances').insert([{ monthly_staff_id: id, company_id: staff.company_id, amount, reason: String(payload.reason || '').trim() || 'Monthly staff advance', status: 'OWNER_APPROVED' }]).select().single(); if (error) throw error; return data; };
const payAdvance = async (id, user) => { assertOwner(user); const { data: advance, error } = await supabase.from('monthly_staff_advances').select('*,monthly_staff!inner(company_id,owner_user_id,full_name,momo_phone)').eq('monthly_staff_advance_id', id).in('monthly_staff.company_id', requireCompanyIds(user)).eq('monthly_staff.owner_user_id', user.user_id).single(); if (error || !advance) throw new Error('Monthly-staff advance was not found in your Owner scope.'); if (advance.status === 'PAID') throw new Error('This advance is already paid.'); if (advance.status !== 'OWNER_APPROVED') throw new Error('Only an Owner-approved monthly-staff advance can be paid.'); const reference = `MONTHLY-ADV-${randomUUID()}`; try { const transaction = await getPaymentProvider().processPayment({ reference_id: reference, amount: Number(advance.amount), receiver_phone: advance.monthly_staff.momo_phone }); const { data, error: updateError } = await supabase.from('monthly_staff_advances').update({ status:'PAID', payment_reference:transaction.reference_id || reference, paid_by:user.user_id, paid_at:new Date().toISOString(), payment_failure_reason:null }).eq('monthly_staff_advance_id', id).select().single(); if (updateError) throw updateError; return data; } catch (paymentError) { await supabase.from('monthly_staff_advances').update({ status:'FAILED', payment_failure_reason:paymentError.message }).eq('monthly_staff_advance_id', id); throw paymentError; } };
const generatePayroll = async (id, payload, user) => { const staff = await get(id, user); const { month, year } = monthPeriod(payload.month, payload.year); const { data: existing } = await supabase.from('monthly_staff_payroll').select('*').eq('monthly_staff_id', id).eq('payroll_month', month).eq('payroll_year', year).maybeSingle(); if (existing) return existing; const { data: advances, error: advanceError } = await supabase.from('monthly_staff_advances').select('amount').eq('monthly_staff_id', id).eq('status', 'PAID').gte('request_date', `${year}-${String(month).padStart(2,'0')}-01`).lte('request_date', `${year}-${String(month).padStart(2,'0')}-31`); if (advanceError) throw advanceError; const gross_salary = Number(staff.monthly_salary); const advance_deduction = (advances || []).reduce((sum, row) => sum + Number(row.amount || 0), 0); const { data, error } = await supabase.from('monthly_staff_payroll').insert([{ monthly_staff_id: id, company_id: staff.company_id, payroll_month: month, payroll_year: year, gross_salary, advance_deduction, net_salary: Math.max(0, gross_salary - advance_deduction) }]).select().single(); if (error) throw error; return data; };
const payPayroll = async (id, user) => { assertOwner(user); const { data: payroll, error } = await supabase.from('monthly_staff_payroll').select('*, monthly_staff!inner(company_id,owner_user_id,full_name,momo_phone)').eq('monthly_staff_payroll_id', id).in('monthly_staff.company_id', requireCompanyIds(user)).eq('monthly_staff.owner_user_id', user.user_id).single(); if (error || !payroll) throw new Error('Monthly payroll was not found in your Owner scope.'); if (payroll.payment_status === 'PAID') throw new Error('This monthly payroll is already paid.'); const reference = `MONTHLY-${randomUUID()}`; try { const transaction = await getPaymentProvider().processPayment({ reference_id: reference, amount: Number(payroll.net_salary), receiver_phone: payroll.monthly_staff.momo_phone }); const { data, error: updateError } = await supabase.from('monthly_staff_payroll').update({ payment_status: 'PAID', payment_reference: transaction.reference_id || reference, paid_by: user.user_id, paid_at: new Date().toISOString(), payment_failure_reason: null }).eq('monthly_staff_payroll_id', id).select().single(); if (updateError) throw updateError; return data; } catch (paymentError) { await supabase.from('monthly_staff_payroll').update({ payment_status: 'FAILED', payment_failure_reason: paymentError.message }).eq('monthly_staff_payroll_id', id); throw paymentError; } };
module.exports = { list, create, requestAdvance, payAdvance, generatePayroll, payPayroll };
