const { randomUUID } = require('crypto');
const supabase = require('../config/supabase');
const { isSuperAdmin, requireCompanyIds } = require('../utils/companyScope');
const { scopeByManager, assertEmployeeManager } = require('../utils/managerScope');
const { getPaymentProvider } = require('./paymentProviders');
const validPhone = (phone) => /^(?:\+?2507[2389]\d{7}|07[2389]\d{7})$/.test(String(phone || '').replace(/[^\d+]/g, ''));

const getConsumptions = async (user) => { let q = supabase.from('worker_consumptions').select('*, employees!inner(employee_code, first_name, last_name, company_id, manager_user_id), shopkeepers(shopkeeper_name, phone)').order('consumption_date', { ascending: false }); if (!isSuperAdmin(user)) q = q.in('company_id', requireCompanyIds(user)); q = scopeByManager(q, user); const { data, error } = await q; if (error) throw error; return data || []; };
const getConsumption = async (id, user) => { const row = (await getConsumptions(user)).find((item) => item.consumption_id === id); if (!row) throw new Error('Worker item not found in your management scope.'); return row; };
const recordConsumption = async ({ employee_id, shopkeeper_id, consumption_date, item_name, quantity = 1, unit_price, remarks }, user) => {
  if (!employee_id || !shopkeeper_id || !consumption_date || !item_name?.trim() || Number(quantity) <= 0 || Number(unit_price) < 0) throw new Error('Worker, shopkeeper, date, item, positive quantity, and valid price are required.');
  let eq = supabase.from('employees').select('employee_id, company_id, manager_user_id').eq('employee_id', employee_id); if (!isSuperAdmin(user)) eq = eq.in('company_id', requireCompanyIds(user)); const { data: employee, error } = await eq.single(); if (error || !employee) throw new Error('Employee not found for your company.'); assertEmployeeManager(employee, user);
  let sq = supabase.from('shopkeepers').select('*').eq('shopkeeper_id', shopkeeper_id).eq('active', true); if (!isSuperAdmin(user)) sq = sq.in('company_id', requireCompanyIds(user)); sq = scopeByManager(sq, user); const { data: shop, error: shopError } = await sq.single(); if (shopError || !shop || shop.manager_user_id !== employee.manager_user_id) throw new Error('Select an active shopkeeper assigned to this worker’s manager.');
  const total = Number((Number(quantity) * Number(unit_price)).toFixed(2)); const { data, error: insertError } = await supabase.from('worker_consumptions').insert([{ company_id: employee.company_id, manager_user_id: employee.manager_user_id, employee_id, shopkeeper_id, consumption_date, item_name: item_name.trim(), quantity: Number(quantity), unit_price: Number(unit_price), total_amount: total, remaining_balance: total, recorded_by: user.user_id, remarks: remarks || null, approval_status: 'PENDING_MANAGER', shopkeeper_payment_status: 'UNPAID' }]).select().single(); if (insertError) throw insertError; return data;
};
const reviewConsumption = async (id, decision, comments, user) => { const item = await getConsumption(id, user); const now = new Date().toISOString(); let update; if (user.role_name === 'MANAGER') { if (!['PENDING_MANAGER', 'CHANGES_REQUESTED'].includes(item.approval_status)) throw new Error('This item is not awaiting manager approval.'); update = decision === 'approve' ? { approval_status: 'PENDING_OWNER', manager_approved_by: user.user_id, manager_approved_at: now } : { approval_status: 'CHANGES_REQUESTED', approval_comments: comments || 'Changes requested' }; } else if (user.role_name === 'OWNER') { if (item.approval_status !== 'PENDING_OWNER') throw new Error('Manager approval is required first.'); update = decision === 'approve' ? { approval_status: 'OWNER_APPROVED', owner_approved_by: user.user_id, owner_approved_at: now } : { approval_status: 'CHANGES_REQUESTED', approval_comments: comments || 'Changes requested' }; } else throw new Error('Only manager or owner can approve worker items.'); const { data, error } = await supabase.from('worker_consumptions').update(update).eq('consumption_id', id).select().single(); if (error) throw error; return data; };
const payConsumption = async (id, user) => { if (user.role_name !== 'OWNER' && !isSuperAdmin(user)) throw new Error('Only the owner can pay a shopkeeper.'); const item = await getConsumption(id, user); if (item.approval_status !== 'OWNER_APPROVED' || item.shopkeeper_payment_status === 'PAID') throw new Error('Only owner-approved, unpaid worker items can be paid.'); if (!validPhone(item.shopkeepers?.phone)) throw new Error('The shopkeeper has no valid payment phone number.'); const { data: existing } = await supabase.from('shopkeeper_payments').select('shopkeeper_payment_id').eq('consumption_id', id).maybeSingle(); if (existing) throw new Error('This worker item has already been paid.'); const reference = `SHOP-${randomUUID()}`; const transaction = await getPaymentProvider().processPayment({ reference_id: reference, amount: Number(item.total_amount), phone: item.shopkeepers.phone }); const now = new Date().toISOString(); const { error: paymentError } = await supabase.from('shopkeeper_payments').insert([{ consumption_id: id, shopkeeper_id: item.shopkeeper_id, company_id: item.company_id, amount: item.total_amount, payment_status: 'PAID', provider_name: 'INTERNAL_TEST', transaction_reference: transaction.reference_id || reference, provider_response: transaction, paid_by: user.user_id, paid_at: now }]); if (paymentError) throw paymentError; const { data, error } = await supabase.from('worker_consumptions').update({ approval_status: 'PAID', shopkeeper_payment_status: 'PAID', shopkeeper_payment_reference: transaction.reference_id || reference, paid_at: now }).eq('consumption_id', id).select().single(); if (error) throw error; return data; };
const payAllConsumptions = async ({ manager_user_id } = {}, user) => { if (user.role_name !== 'OWNER' && !isSuperAdmin(user)) throw new Error('Only the owner can pay shopkeepers.'); const eligible = (await getConsumptions(user)).filter((row) => row.approval_status === 'OWNER_APPROVED' && row.shopkeeper_payment_status !== 'PAID' && (!manager_user_id || row.manager_user_id === manager_user_id)); const failed = []; let paid = 0; for (const row of eligible) { try { await payConsumption(row.consumption_id, user); paid += 1; } catch (error) { failed.push({ consumption_id: row.consumption_id, message: error.message }); } } return { total: eligible.length, paid, failed }; };
module.exports = { recordConsumption, getConsumptions, reviewConsumption, payConsumption, payAllConsumptions };
